import type { SiteLocale } from "@/lib/i18n/config";
const copy = {
  invalidCountry: ["Seleciona um país válido.", "Select a valid country.", "Sélectionnez un pays valide.", "Selecciona un país válido.", "Wählen Sie ein gültiges Land.", "Seleziona un paese valido."],
  invalidPostal: ["Confirma o código postal português (0000-000).", "Check the Portuguese postcode (0000-000).", "Vérifiez le code postal portugais (0000-000).", "Comprueba el código postal portugués (0000-000).", "Prüfen Sie die portugiesische Postleitzahl (0000-000).", "Verifica il codice postale portoghese (0000-000)."],
  internationalReview: ["Para este destino, contacta-nos para confirmar os impostos e a entrega antes do pagamento. O teu carrinho fica guardado.", "For this destination, contact us to confirm taxes and delivery before payment. Your cart is saved.", "Pour cette destination, contactez-nous pour confirmer les taxes et la livraison avant paiement. Votre panier est conservé.", "Para este destino, contáctanos para confirmar impuestos y entrega antes del pago. Tu carrito queda guardado.", "Kontaktieren Sie uns für dieses Lieferziel, um Steuern und Lieferung vor der Zahlung zu bestätigen. Ihr Warenkorb bleibt gespeichert.", "Per questa destinazione, contattaci per confermare imposte e consegna prima del pagamento. Il carrello rimane salvato."],
  currencyReview: ["O pagamento está disponível em EUR. Contacta-nos para confirmar esta encomenda.", "Payment is available in EUR. Contact us to confirm this order.", "Le paiement est disponible en EUR. Contactez-nous pour confirmer cette commande.", "El pago está disponible en EUR. Contáctanos para confirmar este pedido.", "Die Zahlung ist in EUR verfügbar. Kontaktieren Sie uns, um diese Bestellung zu bestätigen.", "Il pagamento è disponibile in EUR. Contattaci per confermare questo ordine."],
  contact: ["Contactar a 360", "Contact 360", "Contacter 360", "Contactar con 360", "360 kontaktieren", "Contatta 360"],
  edit: ["Alterar morada", "Change address", "Modifier l’adresse", "Cambiar dirección", "Adresse ändern", "Modifica indirizzo"],
  display: ["Moeda de referência", "Reference currency", "Devise de référence", "Moneda de referencia", "Referenzwährung", "Valuta di riferimento"],
  estimate: ["Valor aproximado. Pagamento em EUR; o teu banco pode aplicar outro câmbio e comissões.", "Approximate value. Payment in EUR; your bank may apply a different exchange rate and fees.", "Valeur approximative. Paiement en EUR ; votre banque peut appliquer un autre taux et des frais.", "Valor aproximado. Pago en EUR; tu banco puede aplicar otro cambio y comisiones.", "Ungefährer Wert. Zahlung in EUR; Ihre Bank kann einen anderen Wechselkurs und Gebühren anwenden.", "Valore indicativo. Pagamento in EUR; la banca può applicare un cambio diverso e commissioni."],
  unavailable: ["Conversão indisponível. O total em EUR mantém-se válido.", "Conversion unavailable. The EUR total remains valid.", "Conversion indisponible. Le total en EUR reste valable.", "Conversión no disponible. El total en EUR sigue siendo válido.", "Umrechnung nicht verfügbar. Der EUR-Gesamtbetrag bleibt gültig.", "Conversione non disponibile. Il totale in EUR rimane valido."],
} as const;
export function marketText(key: keyof typeof copy, locale: SiteLocale): string {
  return copy[key][["pt", "en", "fr", "es", "de", "it"].indexOf(locale)];
}
