import type { SiteLocale } from "@/lib/i18n/config";
export type SalesAgent = {
  id: string;
  user_id: string | null;
  account_kind: "new_account" | "existing_account";
  full_name: string;
  email: string;
  phone: string;
  company_name: string;
  tax_id: string;
  billing_address: string;
  iban: string;
  countries: string[];
  locale: SiteLocale;
  status: "draft" | "invited" | "active" | "suspended";
  supplier_rate_bps: number | null;
  manual_rate_bps: number | null;
  hold_days: number | null;
  attribution_months: number | null;
  recurring: boolean | null;
  commission_enabled: boolean;
  monthly_target_cents: number;
  starts_on: string;
  ends_on: string | null;
  invitation_sent_at: string | null;
  invitation_error: string | null;
  created_at: string;
  updated_at: string;
};
export type SalesAssignment = {
  id: string;
  agent_id: string;
  customer_user_id: string;
  customer_name: string;
  customer_email: string;
  starts_at: string;
  expires_at: string | null;
  ended_at: string | null;
};
export type SalesContact = {
  id: string;
  agent_id: string;
  name: string;
  email: string;
  phone: string;
  company_name: string;
  country_code: string;
  stage: string;
  notes: string;
  next_contact_on: string | null;
  created_at: string;
};
export type SalesCommission = {
  order_id: string;
  agent_id: string;
  order_number: string;
  customer_name: string;
  currency: string;
  supplier_base_cents: number;
  manual_base_cents: number;
  original_cents: number;
  earned_cents: number;
  paid_cents: number;
  eligible_at: string | null;
  state: string;
  review_required: boolean;
  approved_at: string | null;
  approved_cents: number | null;
  refund_cents: number;
  rule_snapshot: Record<string, unknown>;
  created_at: string;
  updated_at: string;
};
export type SalesPayout = {
  id: string;
  agent_id: string;
  period: string;
  currency: string;
  amount_cents: number;
  reference: string;
  proof_path: string | null;
  paid_at: string;
  created_at: string;
};
export type SalesActionState = {
  success: boolean;
  message: string;
  id?: string;
};
