import type { SiteLocale } from "@/lib/i18n/config";

export const STATUS_LABELS: Record<SiteLocale, Record<string, string>> = {
  pt: {
    pending: "A aguardar pagamento", succeeded: "Pagamento confirmado", partially_refunded: "Reembolso parcial", approved: "Aprovada", rejected: "Requer revisão",
    pending_payment: "A aguardar pagamento", paid: "Pagamento confirmado",
    processing: "Em preparação", sent_to_supplier: "Em processamento",
    supplier_confirmed: "Confirmada", in_production: "Em produção",
    shipped: "Expedida", delivered: "Entregue", cancelled: "Cancelada",
    refunded: "Reembolsada", failed: "Necessita de atenção",
    unfulfilled: "Em preparação", partially_fulfilled: "Parcialmente preparada",
    fulfilled: "Preparada",
    WAITING_ART_WORK: "A aguardar elementos de personalização",
    PROCESSING: "Em processamento", PRODUCTION: "Em produção",
    WAITING_STOCK: "A aguardar disponibilidade", PROCESSED: "Preparada",
    PENDING_MOCKUP_APPROVAL: "Maquete pendente de aprovação",
    INVOICED: "Faturada", SENT: "Expedida", SHIPPED: "Expedida",
    CANCELED: "Cancelada", CANCELLED: "Cancelada",
  },
  en: {
    pending: "Awaiting payment", succeeded: "Payment confirmed", partially_refunded: "Partially refunded", approved: "Approved", rejected: "Needs revision",
    pending_payment: "Awaiting payment", paid: "Payment confirmed",
    processing: "Being prepared", sent_to_supplier: "Processing",
    supplier_confirmed: "Confirmed", in_production: "In production",
    shipped: "Shipped", delivered: "Delivered", cancelled: "Cancelled",
    refunded: "Refunded", failed: "Needs attention",
    unfulfilled: "Being prepared", partially_fulfilled: "Partially prepared",
    fulfilled: "Prepared",
    WAITING_ART_WORK: "Awaiting customisation files", PROCESSING: "Processing",
    PRODUCTION: "In production", WAITING_STOCK: "Awaiting availability",
    PROCESSED: "Prepared", PENDING_MOCKUP_APPROVAL: "Proof awaiting approval",
    INVOICED: "Invoiced", SENT: "Shipped", SHIPPED: "Shipped",
    CANCELED: "Cancelled", CANCELLED: "Cancelled",
  },
  fr: {
    pending: "En attente de paiement", succeeded: "Paiement confirmé", partially_refunded: "Remboursement partiel", approved: "Approuvée", rejected: "À réviser",
    pending_payment: "En attente de paiement", paid: "Paiement confirmé",
    processing: "En préparation", sent_to_supplier: "En cours de traitement",
    supplier_confirmed: "Confirmée", in_production: "En production",
    shipped: "Expédiée", delivered: "Livrée", cancelled: "Annulée",
    refunded: "Remboursée", failed: "Nécessite votre attention",
    unfulfilled: "En préparation", partially_fulfilled: "Partiellement préparée",
    fulfilled: "Préparée",
    WAITING_ART_WORK: "En attente des éléments de personnalisation",
    PROCESSING: "En cours de traitement", PRODUCTION: "En production",
    WAITING_STOCK: "En attente de disponibilité", PROCESSED: "Préparée",
    PENDING_MOCKUP_APPROVAL: "Maquette en attente d’approbation",
    INVOICED: "Facturée", SENT: "Expédiée", SHIPPED: "Expédiée",
    CANCELED: "Annulée", CANCELLED: "Annulée",
  },

es: {
    pending: "Pendiente de pago", succeeded: "Pago confirmado", partially_refunded: "Reembolso parcial", approved: "Aprobado", rejected: "Necesita revisi\u00F3n",
    pending_payment: "Pendiente de pago", paid: "Pago confirmado",
    processing: "En preparaci\u00F3n", sent_to_supplier: "En proceso",
    supplier_confirmed: "Confirmado", in_production: "En producci\u00F3n",
    shipped: "Enviado", delivered: "Entregado", cancelled: "Cancelado",
    refunded: "Reembolsado", failed: "Requiere atenci\u00F3n",
    unfulfilled: "En preparaci\u00F3n", partially_fulfilled: "Preparaci\u00F3n parcial",
    fulfilled: "Preparado",
    WAITING_ART_WORK: "Pendiente de archivos de personalizaci\u00F3n", PROCESSING: "En proceso",
    PRODUCTION: "En producci\u00F3n", WAITING_STOCK: "Pendiente de disponibilidad",
    PROCESSED: "Preparado", PENDING_MOCKUP_APPROVAL: "Prueba pendiente de aprobaci\u00F3n",
    INVOICED: "Facturado", SENT: "Enviado", SHIPPED: "Enviado",
    CANCELED: "Cancelado", CANCELLED: "Cancelado",
},
de: {
    pending: "Zahlung ausstehend", succeeded: "Zahlung best\u00E4tigt", partially_refunded: "Teilweise erstattet", approved: "Freigegeben", rejected: "\u00DCberarbeitung erforderlich",
    pending_payment: "Zahlung ausstehend", paid: "Zahlung best\u00E4tigt",
    processing: "Wird vorbereitet", sent_to_supplier: "In Bearbeitung",
    supplier_confirmed: "Best\u00E4tigt", in_production: "In Produktion",
    shipped: "Versendet", delivered: "Zugestellt", cancelled: "Storniert",
    refunded: "Erstattet", failed: "Kl\u00E4rung erforderlich",
    unfulfilled: "Wird vorbereitet", partially_fulfilled: "Teilweise vorbereitet",
    fulfilled: "Vorbereitet",
    WAITING_ART_WORK: "Personalisierungsdateien ausstehend", PROCESSING: "In Bearbeitung",
    PRODUCTION: "In Produktion", WAITING_STOCK: "Verf\u00FCgbarkeit ausstehend",
    PROCESSED: "Vorbereitet", PENDING_MOCKUP_APPROVAL: "Korrekturabzug wartet auf Freigabe",
    INVOICED: "Rechnung gestellt", SENT: "Versendet", SHIPPED: "Versendet",
    CANCELED: "Storniert", CANCELLED: "Storniert",
},
it: {
    pending: "In attesa di pagamento", succeeded: "Pagamento confermato", partially_refunded: "Rimborsato parzialmente", approved: "Approvato", rejected: "Revisione necessaria",
    pending_payment: "In attesa di pagamento", paid: "Pagamento confermato",
    processing: "In preparazione", sent_to_supplier: "In elaborazione",
    supplier_confirmed: "Confermato", in_production: "In produzione",
    shipped: "Spedito", delivered: "Consegnato", cancelled: "Annullato",
    refunded: "Rimborsato", failed: "Richiede attenzione",
    unfulfilled: "In preparazione", partially_fulfilled: "Preparato parzialmente",
    fulfilled: "Preparato",
    WAITING_ART_WORK: "In attesa dei file di personalizzazione", PROCESSING: "In elaborazione",
    PRODUCTION: "In produzione", WAITING_STOCK: "In attesa di disponibilit\u00E0",
    PROCESSED: "Preparato", PENDING_MOCKUP_APPROVAL: "Prova in attesa di approvazione",
    INVOICED: "Fatturato", SENT: "Spedito", SHIPPED: "Spedito",
    CANCELED: "Annullato", CANCELLED: "Annullato",
},
};


export function customerStatus(status: string, locale: SiteLocale): string {
  return STATUS_LABELS[locale][status] ?? ({pt:"Em atualização",en:"Being updated",fr:"En cours de mise à jour",
es: "En actualizaci\u00F3n",
de: "Wird aktualisiert",
it: "In aggiornamento",
})[locale];
}
