import type { SiteLocale } from "@/lib/i18n/config";

export const authCopy = {
  pt: {
    loginTitle: "Entrar na plataforma", loginIntro: "Acede à tua Área de Cliente ou ao backoffice de Administração.", registrationSuccess: "Conta criada com sucesso. Enviámos um email de confirmação para o endereço indicado. Confirma a conta através desse email antes de iniciares sessão.", password: "Palavra-passe", signingIn: "A entrar...", signIn: "Entrar", forgot: "Esqueci-me da palavra-passe", noAccount: "Ainda não tens conta?", createAccount: "Criar conta",
    registerIntro: "Cria uma conta para guardares os teus dados, acompanhares encomendas, pedidos e maquetes.", fullName: "Nome completo", namePlaceholder: "Nome e apelido", professionalEmail: "E-mail profissional", passwordRule: "Mínimo de 8 caracteres, incluindo pelo menos uma letra e um número.", passwordPlaceholder: "Mínimo 8 caracteres, com letras e números", confirmPassword: "Confirmar palavra-passe", repeatPassword: "Repetir palavra-passe", creating: "A criar conta...", hasAccount: "Já tens conta?",
    recoverTitle: "Recuperar palavra-passe", recoverIntro: "Recebe no teu e-mail uma ligação segura para definires uma nova palavra-passe.", sending: "A enviar...", sendLink: "Enviar ligação", backLogin: "Voltar ao login", newPasswordTitle: "Nova palavra-passe", newPassword: "Nova palavra-passe", changing: "A alterar...", changePassword: "Alterar palavra-passe", continue: "Continuar",
  },
  en: {
    loginTitle: "Sign in", loginIntro: "Access your Customer Area or the administration back office.", registrationSuccess: "Account created successfully. We sent a confirmation email to the address provided. Confirm your account from that email before signing in.", password: "Password", signingIn: "Signing in...", signIn: "Sign in", forgot: "Forgot your password?", noAccount: "Don’t have an account?", createAccount: "Create account",
    registerIntro: "Create an account to save your details and follow orders, requests and artwork proofs.", fullName: "Full name", namePlaceholder: "First and last name", professionalEmail: "Work email", passwordRule: "At least 8 characters, including one letter and one number.", passwordPlaceholder: "At least 8 characters, with letters and numbers", confirmPassword: "Confirm password", repeatPassword: "Repeat password", creating: "Creating account...", hasAccount: "Already have an account?",
    recoverTitle: "Reset password", recoverIntro: "Receive a secure link by email to set a new password.", sending: "Sending...", sendLink: "Send reset link", backLogin: "Back to sign in", newPasswordTitle: "New password", newPassword: "New password", changing: "Updating...", changePassword: "Update password", continue: "Continue",
  },
  fr: {
    loginTitle: "Se connecter", loginIntro: "Accédez à votre Espace Client ou au back-office d’administration.", registrationSuccess: "Compte créé avec succès. Nous avons envoyé un e-mail de confirmation à l’adresse indiquée. Confirmez votre compte avant de vous connecter.", password: "Mot de passe", signingIn: "Connexion...", signIn: "Se connecter", forgot: "Mot de passe oublié ?", noAccount: "Vous n’avez pas de compte ?", createAccount: "Créer un compte",
    registerIntro: "Créez un compte pour enregistrer vos coordonnées et suivre commandes, demandes et maquettes.", fullName: "Nom complet", namePlaceholder: "Prénom et nom", professionalEmail: "E-mail professionnel", passwordRule: "Au moins 8 caractères, dont une lettre et un chiffre.", passwordPlaceholder: "Au moins 8 caractères, avec lettres et chiffres", confirmPassword: "Confirmer le mot de passe", repeatPassword: "Répéter le mot de passe", creating: "Création du compte...", hasAccount: "Vous avez déjà un compte ?",
    recoverTitle: "Réinitialiser le mot de passe", recoverIntro: "Recevez par e-mail un lien sécurisé pour définir un nouveau mot de passe.", sending: "Envoi...", sendLink: "Envoyer le lien", backLogin: "Retour à la connexion", newPasswordTitle: "Nouveau mot de passe", newPassword: "Nouveau mot de passe", changing: "Modification...", changePassword: "Modifier le mot de passe", continue: "Continuer",
  },
} satisfies Record<SiteLocale, Record<string, string>>;

export const customerCopy = {
  pt: { dashboard: "Voltar ao dashboard", area: "Área Cliente", hello: "Olá", welcome: "bem-vindo", intro: "Acompanha as tuas encomendas, pedidos de orçamento, carrinho e dados comerciais da tua conta 360 Merchandising.", customer: "Cliente", logout: "Sair", account: "Conta", personalData: "Dados pessoais", manageData: "Gerir dados", orders: "Encomendas", viewOrders: "Ver encomendas", requests: "Pedidos personalizados", viewRequests: "Ver pedidos", cart: "Carrinho", active: "Ativo", openCart: "Abrir carrinho", recentOrders: "Encomendas recentes", recentOrdersText: "Compra direta, pagamento e estado de processamento.", noOrders: "Ainda não existem encomendas. Quando comprares online, vais poder acompanhar aqui o estado da encomenda.", requestsText: "Orçamentos para pedidos especiais ou personalizações complexas.", noRequests: "Ainda não existem pedidos personalizados associados à tua conta.", quote: "Pedido de orçamento", ordersTitle: "As minhas encomendas", ordersIntro: "Consulta aqui as encomendas realizadas na 360 Merchandising.", status: "Estado", payment: "Pagamento", dataTitle: "Dados da conta", dataIntro: "Gere os contactos, dados de faturação e moradas usados nas encomendas. Podes guardar várias moradas de entrega e escolher a preferida.", requestsTitle: "Pedidos personalizados", requestsIntro: "Consulta os pedidos de orçamento ou personalização submetidos através da 360 Merchandising.", requestFallback: "Pedido personalizado" },
  en: { dashboard: "Back to dashboard", area: "Customer Area", hello: "Hello", welcome: "welcome", intro: "Track your orders, quote requests, cart and business details for your 360 Merchandising account.", customer: "Customer", logout: "Sign out", account: "Account", personalData: "Personal details", manageData: "Manage details", orders: "Orders", viewOrders: "View orders", requests: "Custom requests", viewRequests: "View requests", cart: "Cart", active: "Active", openCart: "Open cart", recentOrders: "Recent orders", recentOrdersText: "Direct purchases, payments and processing status.", noOrders: "There are no orders yet. When you buy online, you can track the order status here.", requestsText: "Quotes for special requests or complex customisation.", noRequests: "There are no custom requests associated with your account yet.", quote: "Quote request", ordersTitle: "My orders", ordersIntro: "View the orders placed with 360 Merchandising.", status: "Status", payment: "Payment", dataTitle: "Account details", dataIntro: "Manage the contacts, billing details and addresses used for orders. You can save several delivery addresses and choose your preferred one.", requestsTitle: "Custom requests", requestsIntro: "View quote or customisation requests submitted through 360 Merchandising.", requestFallback: "Custom request" },
  fr: { dashboard: "Retour au tableau de bord", area: "Espace Client", hello: "Bonjour", welcome: "bienvenue", intro: "Suivez vos commandes, demandes de devis, panier et coordonnées professionnelles de votre compte 360 Merchandising.", customer: "Client", logout: "Se déconnecter", account: "Compte", personalData: "Données personnelles", manageData: "Gérer les données", orders: "Commandes", viewOrders: "Voir les commandes", requests: "Demandes personnalisées", viewRequests: "Voir les demandes", cart: "Panier", active: "Actif", openCart: "Ouvrir le panier", recentOrders: "Commandes récentes", recentOrdersText: "Achats directs, paiements et état de traitement.", noOrders: "Aucune commande pour le moment. Après un achat en ligne, vous pourrez suivre son état ici.", requestsText: "Devis pour demandes spéciales ou personnalisations complexes.", noRequests: "Aucune demande personnalisée n’est encore associée à votre compte.", quote: "Demande de devis", ordersTitle: "Mes commandes", ordersIntro: "Consultez les commandes passées auprès de 360 Merchandising.", status: "État", payment: "Paiement", dataTitle: "Données du compte", dataIntro: "Gérez les contacts, données de facturation et adresses utilisés pour les commandes. Vous pouvez enregistrer plusieurs adresses de livraison et choisir votre préférée.", requestsTitle: "Demandes personnalisées", requestsIntro: "Consultez les demandes de devis ou de personnalisation envoyées via 360 Merchandising.", requestFallback: "Demande personnalisée" },
} satisfies Record<SiteLocale, Record<string, string>>;

export function authActionMessages(locale: SiteLocale) {
  return locale === "en" ? { required: "Complete all required fields.", loginRequired: "Enter your email and password.", invalid: "Invalid sign-in details.", inactive: "This account is inactive. Contact customer support.", unexpectedLogin: "Unexpected sign-in error.", passwordRule: "The password must contain at least 8 characters, including one letter and one number.", mismatch: "The passwords do not match.", createFailed: "The account could not be created. Try again.", unexpectedCreate: "Unexpected account creation error.", emailRequired: "Enter your email address.", resetSent: "If an account exists for this email, you will receive a link to set a new password.", expired: "The link has expired. Request another password reset.", updateFailed: "The password could not be updated.", updateSuccess: "Password updated successfully. You can continue." }
    : locale === "fr" ? { required: "Remplissez tous les champs obligatoires.", loginRequired: "Saisissez votre e-mail et votre mot de passe.", invalid: "Identifiants incorrects.", inactive: "Ce compte est inactif. Contactez le service client.", unexpectedLogin: "Erreur inattendue lors de la connexion.", passwordRule: "Le mot de passe doit contenir au moins 8 caractères, dont une lettre et un chiffre.", mismatch: "Les mots de passe ne correspondent pas.", createFailed: "Impossible de créer le compte. Réessayez.", unexpectedCreate: "Erreur inattendue lors de la création du compte.", emailRequired: "Saisissez votre adresse e-mail.", resetSent: "Si un compte existe pour cet e-mail, vous recevrez un lien pour définir un nouveau mot de passe.", expired: "Le lien a expiré. Demandez une nouvelle réinitialisation.", updateFailed: "Impossible de modifier le mot de passe.", updateSuccess: "Mot de passe modifié avec succès. Vous pouvez continuer." }
      : { required: "Preenche todos os campos.", loginRequired: "Preenche o e-mail e a palavra-passe.", invalid: "Dados de acesso inválidos.", inactive: "Esta conta está inativa. Contacta o apoio ao cliente.", unexpectedLogin: "Erro inesperado ao iniciar sessão.", passwordRule: "A palavra-passe deve ter no mínimo 8 caracteres e incluir pelo menos uma letra e um número.", mismatch: "As palavras-passe não coincidem.", createFailed: "Não foi possível criar a conta. Tenta novamente.", unexpectedCreate: "Erro técnico inesperado ao criar conta.", emailRequired: "Indica o teu endereço de e-mail.", resetSent: "Se existir uma conta com este e-mail, receberás uma ligação para definir uma nova palavra-passe.", expired: "A ligação expirou. Solicita uma nova recuperação.", updateFailed: "Não foi possível alterar a palavra-passe.", updateSuccess: "Palavra-passe alterada com sucesso. Já podes continuar." };
}
