import type { SiteLocale } from "@/lib/i18n/config";

const messages = {
  pt: {
    common: { backHome: "Voltar à página inicial", backCategories: "Voltar às categorias", searchProducts: "Pesquisar produtos", viewProducts: "Ver produtos", product: "produto", products: "produtos", available: "disponíveis", retry: "Tenta novamente.", quote: "Sob consulta", stock: "Stock", quantity: "Quantidade", personalization: "Personalização", setup: "Preparação", extras: "Extras", vat: "IVA", total: "Total", confirm: "A confirmar", units: "un." },
    catalog: { eyebrow: "Catálogo", title: "Categorias de produtos", intro: "Explora o catálogo por categorias e encontra rapidamente produtos para campanhas, eventos, equipas, clientes e ações empresariais.", loadError: "Não foi possível carregar as categorias.", emptyTitle: "Ainda não existem categorias disponíveis", emptyText: "O catálogo está a ser preparado.", searchEyebrow: "Pesquisa", searchTitle: "Pesquisa de produtos", searchIntro: "Encontra brindes promocionais, merchandising corporativo, gifts empresariais e vestuário promocional para campanhas, eventos e equipas.", placeholder: "Pesquisar por produto, SKU, material, marca ou categoria", type: "Tipo", allTypes: "Todos os tipos", material: "Material", allMaterials: "Todos os materiais", customisation: "Personalização", all: "Todos", customisable: "Personalizáveis", notCustomisable: "Não personalizáveis", sort: "Ordenar", featuredFirst: "Destaques primeiro", newest: "Mais recentes", nameAsc: "Nome A-Z", nameDesc: "Nome Z-A", shown: "produto(s) apresentado(s)", start: "Introduz uma pesquisa ou usa os filtros para encontrar produtos.", clear: "Limpar pesquisa", readyTitle: "Pesquisa pronta a usar", readyText: "Escreve o nome de um produto, SKU, material ou marca. Também podes usar os filtros por tipo, material ou personalização.", noResults: "Sem resultados", noResultsText: "Experimenta pesquisar por garrafa, caneca, t-shirt, algodão, metal ou SKU.", featured: "Destaque", customizable: "Personalizável", noImage: "Sem imagem disponível", from: "Desde", viewProduct: "Ver produto" },
    cart: { continueShopping: "Continuar a comprar", title: "Carrinho", intro: "Revê os produtos e os valores antes de avançar para o checkout.", unit: "Unitário", summary: "Resumo", checkout: "Avançar para checkout", secure: "O pagamento será processado de forma segura através da Stripe.", freeShipping: "Portes grátis em encomendas de valor igual ou superior a 50 €.", freeShippingUnlocked: "Já tens portes grátis nesta encomenda.", freeShippingRemaining: "Adiciona mais {amount} para ter portes grátis.", empty: "O carrinho está vazio", emptyText: "Adiciona produtos ao carrinho para preparar a tua encomenda.", find: "Procurar produtos" },
    checkout: { back: "Voltar ao carrinho", destination: "Destino", detailsAddress: "Dados e morada", shipping: "Expedição", shippingTime: "Transporte e prazo", payment: "Pagamento", reviewPayment: "Revisão e pagamento", step: "Passo 1 de 3", title: "Destino da encomenda", intro: "Confirma os dados do cliente e indica a morada onde pretendes receber a encomenda.", order: "Encomenda", summary: "Resumo", configured: "Personalização configurada", location: "Local", technique: "Técnica", logo: "Logótipo", notUploaded: "Ainda não carregado", shippingCalc: "A calcular", currentTotal: "Total atual", taxNote: "O transporte e o IVA serão adicionados antes do pagamento.", next: "Próximo passo", nextText: "Na expedição poderás escolher o método de transporte, consultar o prazo e confirmar o respetivo custo.", securePayment: "Pagamento seguro", secureText: "O pagamento só será pedido depois da escolha do transporte e da revisão do valor final." },
    product: { back: "Voltar às categorias", backTo: "Voltar a", backProduct: "Voltar ao produto", customizeStep: "Passo 2 · Personalização", customizeIntro: "Escolhe a localização e a técnica, carrega o logótipo e confirma a maquete para avançar diretamente para o checkout.", colourSize: "Cor / tamanho", selected: "Selecionado", noAreas: "Este produto ainda não tem áreas de personalização disponíveis", noAreasText: "Pode voltar ao produto e adicionar ao carrinho sem personalização." },
    header: { categories: "Categorias", guides: "Guias B2B", help: "Ajuda", search: "Pesquisar", cart: "Carrinho", account: "Área Cliente", signIn: "Entrar", admin: "Admin", store: "Ver loja", home: "página inicial" },
    footer: {
      discover: "Descobrir", support: "Apoio", intro: "A forma inteligente de encontrar, personalizar e comprar merchandising para a sua empresa.", trySmart: "Experimentar o Smart Merch", commercialSupport: "Apoio comercial", rights: "Todos os direitos reservados.", complaints: "Livro de Reclamações",
      links: { categories: "Categorias", solutions: "Soluções", applications: "Aplicações", industries: "Indústrias", guides: "Guias", selections: "Seleções 360", customization: "Personalização", sustainability: "Sustentabilidade", blog: "Blog", search: "Pesquisar produtos", about: "Sobre a 360", how: "Como funciona", quality: "Qualidade e transparência", delivery: "Entregas e prazos", methodology: "Metodologia editorial", buy: "Como comprar", request: "Pedido personalizado", account: "Área de cliente", cart: "Carrinho" },
    },
    home: {
      title: "Encontre o merchandising certo em segundos.", intro: "Diga-nos o que precisa, quantas unidades pretende, quanto quer gastar e quando precisa de receber.", badge: "A forma inteligente de comprar merchandising", categories: "Categorias", seeCategories: "Ver categorias", highlights: "Produtos em destaque", categoryTitle: "Brindes & Gifts? Temos.", categoryIntro: "Explore as nossas categorias.", allCategories: "Ver todas as categorias", explore: "Explorar", seeProducts: "Ver produtos", howToBuy: "Como comprar", howTitle: "Da escolha do produto à encomenda em poucos passos.", products: "Produtos", exploreCatalog: "Explorar catálogo", catalogPreparing: "O catálogo está a ser preparado.", b2b: "Vantagens B2B", b2bTitle: "Uma experiência pensada para empresas.", b2bIntro: "A 360 Merchandising foi desenhada para acelerar a compra e a personalização de produtos promocionais, reduzindo pedidos manuais e facilitando a escolha por categoria, cor, stock, quantidade e personalização.", catalog: "Catálogo", ctaTitle: "Encontra o produto certo para a próxima campanha da tua empresa.", from: "Desde", quote: "Sob consulta", stock: "Stock", product: "Ver produto", available: "Produto disponível",
      categoryCards: [
        ["Brindes Promocionais", "Produtos personalizados para campanhas, eventos, feiras e ativações de marca."],
        ["Merchandising Corporativo", "Soluções de branding para empresas, equipas, clientes e ações comerciais."],
        ["Vestuário Promocional", "T-shirts, polos, sweats, casacos e vestuário personalizado para empresas."],
        ["Gifts Empresariais", "Presentes corporativos para clientes, equipas, eventos e campanhas especiais."],
      ],
      steps: [["Escolhe a categoria", "Explora o catálogo por famílias de produto e encontra rapidamente opções para a tua campanha."], ["Define cor e quantidade", "Consulta stock, escalões de preço e disponibilidade antes de avançar com a encomenda."], ["Cria maquete ou compra direto", "Personaliza o produto quando aplicável ou adiciona diretamente ao carrinho."], ["Finaliza a encomenda", "Revê os dados no checkout e confirma a compra de forma simples e segura."]],
      benefits: ["Compra direta online", "Escalões de preço por quantidade", "Stock e cores por produto", "Produtos com personalização disponível", "Catálogo em permanente evolução", "Envios em 24H*"],
      smart: { request: "O que procura?", placeholder: "500 garrafas sustentáveis até 3 € para uma feira", hint: "Pode pesquisar por produto ou simplesmente dizer-nos o que precisa.", suggestions: "Não sei! Aceito as vossas sugestões.", suggestionsHint: "Indique apenas a quantidade e o orçamento disponível.", quantity: "Quantidade", budget: "Orçamento total", submit: "Mostrar sugestões" },
    },
  },
  en: {
    common: { backHome: "Back to homepage", backCategories: "Back to categories", searchProducts: "Search products", viewProducts: "View products", product: "product", products: "products", available: "available", retry: "Please try again.", quote: "Price on request", stock: "Stock", quantity: "Quantity", personalization: "Customisation", setup: "Setup", extras: "Extras", vat: "VAT", total: "Total", confirm: "To be confirmed", units: "units" },
    catalog: { eyebrow: "Catalogue", title: "Product categories", intro: "Browse the catalogue by category and quickly find products for campaigns, events, teams, clients and business initiatives.", loadError: "We could not load the categories.", emptyTitle: "No categories are available yet", emptyText: "The catalogue is being prepared.", searchEyebrow: "Search", searchTitle: "Product search", searchIntro: "Find promotional products, corporate merchandise, business gifts and promotional clothing for campaigns, events and teams.", placeholder: "Search by product, SKU, material, brand or category", type: "Type", allTypes: "All types", material: "Material", allMaterials: "All materials", customisation: "Customisation", all: "All", customisable: "Customisable", notCustomisable: "Not customisable", sort: "Sort", featuredFirst: "Featured first", newest: "Newest", nameAsc: "Name A-Z", nameDesc: "Name Z-A", shown: "product(s) shown", start: "Enter a search or use the filters to find products.", clear: "Clear search", readyTitle: "Ready to search", readyText: "Enter a product name, SKU, material or brand. You can also filter by type, material or customisation.", noResults: "No results", noResultsText: "Try searching for bottle, mug, t-shirt, cotton, metal or a SKU.", featured: "Featured", customizable: "Customisable", noImage: "No image available", from: "From", viewProduct: "View product" },
    cart: { continueShopping: "Continue shopping", title: "Cart", intro: "Review your products and prices before proceeding to checkout.", unit: "Unit price", summary: "Summary", checkout: "Proceed to checkout", secure: "Payment will be processed securely by Stripe.", freeShipping: "Free shipping on orders of €50 or more.", freeShippingUnlocked: "You have unlocked free shipping on this order.", freeShippingRemaining: "Add {amount} more to get free shipping.", empty: "Your cart is empty", emptyText: "Add products to your cart to prepare your order.", find: "Find products" },
    checkout: { back: "Back to cart", destination: "Destination", detailsAddress: "Details and address", shipping: "Shipping", shippingTime: "Delivery and lead time", payment: "Payment", reviewPayment: "Review and payment", step: "Step 1 of 3", title: "Order destination", intro: "Confirm your customer details and enter the address where you want to receive your order.", order: "Order", summary: "Summary", configured: "Customisation configured", location: "Location", technique: "Technique", logo: "Logo", notUploaded: "Not uploaded yet", shippingCalc: "To be calculated", currentTotal: "Current total", taxNote: "Shipping and VAT will be added before payment.", next: "Next step", nextText: "During shipping you can choose the delivery method, check the lead time and confirm its cost.", securePayment: "Secure payment", secureText: "Payment is only requested after selecting shipping and reviewing the final amount." },
    product: { back: "Back to categories", backTo: "Back to", backProduct: "Back to product", customizeStep: "Step 2 · Customisation", customizeIntro: "Choose the location and technique, upload your logo and confirm the mock-up to proceed directly to checkout.", colourSize: "Colour / size", selected: "Selected", noAreas: "This product does not yet have customisation areas available", noAreasText: "You can return to the product and add it to your cart without customisation." },
    header: { categories: "Categories", guides: "B2B Guides", help: "Help", search: "Search", cart: "Cart", account: "My account", signIn: "Sign in", admin: "Admin", store: "View store", home: "homepage" },
    footer: {
      discover: "Discover", support: "Support", intro: "The smart way to find, customise and buy merchandise for your business.", trySmart: "Try Smart Merch", commercialSupport: "Sales support", rights: "All rights reserved.", complaints: "Complaints Book",
      links: { categories: "Categories", solutions: "Solutions", applications: "Applications", industries: "Industries", guides: "Guides", selections: "360 Selections", customization: "Customisation", sustainability: "Sustainability", blog: "Blog", search: "Search products", about: "About 360", how: "How it works", quality: "Quality and transparency", delivery: "Delivery and lead times", methodology: "Editorial methodology", buy: "How to buy", request: "Custom request", account: "My account", cart: "Cart" },
    },
    home: {
      title: "Find the right merchandise in seconds.", intro: "Tell us what you need, how many units you want, your budget and when you need delivery.", badge: "The smart way to buy merchandise", categories: "Categories", seeCategories: "View categories", highlights: "Featured products", categoryTitle: "Promotional products and corporate gifts? We have them.", categoryIntro: "Explore our main product categories.", allCategories: "View all categories", explore: "Explore", seeProducts: "View products", howToBuy: "How to buy", howTitle: "From product selection to order in a few simple steps.", products: "Products", exploreCatalog: "Explore catalogue", catalogPreparing: "The catalogue is being prepared.", b2b: "B2B benefits", b2bTitle: "An experience designed for business.", b2bIntro: "360 Merchandising accelerates the purchase and customisation of promotional products, reducing manual requests and making it easier to choose by category, colour, stock, quantity and customisation.", catalog: "Catalogue", ctaTitle: "Find the right product for your company’s next campaign.", from: "From", quote: "Price on request", stock: "Stock", product: "View product", available: "Product available",
      categoryCards: [["Promotional Products", "Custom products for campaigns, events, trade shows and brand activations."], ["Corporate Merchandise", "Branding solutions for companies, teams, clients and sales campaigns."], ["Promotional Clothing", "T-shirts, polos, sweatshirts, jackets and custom clothing for businesses."], ["Corporate Gifts", "Corporate gifts for clients, teams, events and special campaigns."]],
      steps: [["Choose a category", "Browse product families and quickly find options for your campaign."], ["Select colour and quantity", "Check stock, quantity pricing and availability before ordering."], ["Create a mock-up or buy directly", "Customise the product when available or add it directly to your cart."], ["Complete your order", "Review your details at checkout and confirm your purchase securely."]],
      benefits: ["Buy directly online", "Quantity-based pricing", "Product stock and colours", "Products available for customisation", "Continuously updated catalogue", "24-hour dispatch*"],
      smart: { request: "What are you looking for?", placeholder: "500 sustainable bottles under €3 for a trade show", hint: "Search for a product or simply tell us what you need.", suggestions: "I’m not sure. Show me your suggestions.", suggestionsHint: "Simply enter the quantity and available budget.", quantity: "Quantity", budget: "Total budget", submit: "Show suggestions" },
    },
  },
  fr: {
    common: { backHome: "Retour à l’accueil", backCategories: "Retour aux catégories", searchProducts: "Rechercher des produits", viewProducts: "Voir les produits", product: "produit", products: "produits", available: "disponibles", retry: "Veuillez réessayer.", quote: "Prix sur demande", stock: "Stock", quantity: "Quantité", personalization: "Personnalisation", setup: "Préparation", extras: "Suppléments", vat: "TVA", total: "Total", confirm: "À confirmer", units: "unités" },
    catalog: { eyebrow: "Catalogue", title: "Catégories de produits", intro: "Parcourez le catalogue par catégorie et trouvez rapidement des produits pour vos campagnes, événements, équipes, clients et actions d’entreprise.", loadError: "Impossible de charger les catégories.", emptyTitle: "Aucune catégorie n’est encore disponible", emptyText: "Le catalogue est en cours de préparation.", searchEyebrow: "Recherche", searchTitle: "Recherche de produits", searchIntro: "Trouvez des objets publicitaires, du merchandising d’entreprise, des cadeaux professionnels et des vêtements promotionnels.", placeholder: "Rechercher par produit, SKU, matériau, marque ou catégorie", type: "Type", allTypes: "Tous les types", material: "Matériau", allMaterials: "Tous les matériaux", customisation: "Personnalisation", all: "Tous", customisable: "Personnalisables", notCustomisable: "Non personnalisables", sort: "Trier", featuredFirst: "Produits vedettes d’abord", newest: "Plus récents", nameAsc: "Nom A-Z", nameDesc: "Nom Z-A", shown: "produit(s) affiché(s)", start: "Saisissez une recherche ou utilisez les filtres.", clear: "Effacer la recherche", readyTitle: "Recherche prête", readyText: "Saisissez un nom de produit, un SKU, un matériau ou une marque. Vous pouvez également utiliser les filtres.", noResults: "Aucun résultat", noResultsText: "Essayez bouteille, mug, t-shirt, coton, métal ou un SKU.", featured: "En vedette", customizable: "Personnalisable", noImage: "Image indisponible", from: "À partir de", viewProduct: "Voir le produit" },
    cart: { continueShopping: "Continuer mes achats", title: "Panier", intro: "Vérifiez les produits et les prix avant de passer à la commande.", unit: "Prix unitaire", summary: "Récapitulatif", checkout: "Passer à la commande", secure: "Le paiement sera traité de manière sécurisée par Stripe.", freeShipping: "Livraison gratuite dès 50 € d’achat.", freeShippingUnlocked: "Vous bénéficiez de la livraison gratuite.", freeShippingRemaining: "Ajoutez encore {amount} pour bénéficier de la livraison gratuite.", empty: "Votre panier est vide", emptyText: "Ajoutez des produits au panier pour préparer votre commande.", find: "Rechercher des produits" },
    checkout: { back: "Retour au panier", destination: "Destination", detailsAddress: "Coordonnées et adresse", shipping: "Expédition", shippingTime: "Transport et délai", payment: "Paiement", reviewPayment: "Vérification et paiement", step: "Étape 1 sur 3", title: "Destination de la commande", intro: "Confirmez vos coordonnées et indiquez l’adresse de livraison de la commande.", order: "Commande", summary: "Récapitulatif", configured: "Personnalisation configurée", location: "Emplacement", technique: "Technique", logo: "Logo", notUploaded: "Pas encore téléchargé", shippingCalc: "À calculer", currentTotal: "Total actuel", taxNote: "Le transport et la TVA seront ajoutés avant le paiement.", next: "Étape suivante", nextText: "Lors de l’expédition, vous pourrez choisir le mode de transport, consulter le délai et confirmer son coût.", securePayment: "Paiement sécurisé", secureText: "Le paiement ne sera demandé qu’après le choix du transport et la vérification du montant final." },
    product: { back: "Retour aux catégories", backTo: "Retour à", backProduct: "Retour au produit", customizeStep: "Étape 2 · Personnalisation", customizeIntro: "Choisissez l’emplacement et la technique, téléchargez votre logo et confirmez la maquette pour passer directement à la commande.", colourSize: "Couleur / taille", selected: "Sélectionné", noAreas: "Ce produit ne dispose pas encore de zones de personnalisation", noAreasText: "Vous pouvez revenir au produit et l’ajouter au panier sans personnalisation." },
    header: { categories: "Catégories", guides: "Guides B2B", help: "Aide", search: "Rechercher", cart: "Panier", account: "Mon compte", signIn: "Se connecter", admin: "Admin", store: "Voir la boutique", home: "page d’accueil" },
    footer: {
      discover: "Découvrir", support: "Assistance", intro: "La façon intelligente de trouver, personnaliser et acheter du merchandising pour votre entreprise.", trySmart: "Essayer Smart Merch", commercialSupport: "Assistance commerciale", rights: "Tous droits réservés.", complaints: "Livre de réclamations",
      links: { categories: "Catégories", solutions: "Solutions", applications: "Applications", industries: "Secteurs", guides: "Guides", selections: "Sélections 360", customization: "Personnalisation", sustainability: "Durabilité", blog: "Blog", search: "Rechercher des produits", about: "À propos de 360", how: "Comment ça marche", quality: "Qualité et transparence", delivery: "Livraison et délais", methodology: "Méthodologie éditoriale", buy: "Comment acheter", request: "Demande personnalisée", account: "Mon compte", cart: "Panier" },
    },
    home: {
      title: "Trouvez le bon merchandising en quelques secondes.", intro: "Indiquez-nous vos besoins, la quantité souhaitée, votre budget et la date de livraison.", badge: "La façon intelligente d’acheter du merchandising", categories: "Catégories", seeCategories: "Voir les catégories", highlights: "Produits en vedette", categoryTitle: "Objets publicitaires et cadeaux d’entreprise ? Nous les avons.", categoryIntro: "Découvrez nos principales catégories de produits.", allCategories: "Voir toutes les catégories", explore: "Découvrir", seeProducts: "Voir les produits", howToBuy: "Comment acheter", howTitle: "Du choix du produit à la commande en quelques étapes simples.", products: "Produits", exploreCatalog: "Découvrir le catalogue", catalogPreparing: "Le catalogue est en cours de préparation.", b2b: "Avantages B2B", b2bTitle: "Une expérience conçue pour les entreprises.", b2bIntro: "360 Merchandising accélère l’achat et la personnalisation de produits promotionnels, réduit les demandes manuelles et facilite le choix par catégorie, couleur, stock, quantité et personnalisation.", catalog: "Catalogue", ctaTitle: "Trouvez le produit idéal pour la prochaine campagne de votre entreprise.", from: "À partir de", quote: "Prix sur demande", stock: "Stock", product: "Voir le produit", available: "Produit disponible",
      categoryCards: [["Objets publicitaires", "Produits personnalisés pour campagnes, événements, salons et activations de marque."], ["Merchandising d’entreprise", "Solutions de marque pour entreprises, équipes, clients et actions commerciales."], ["Vêtements promotionnels", "T-shirts, polos, sweat-shirts, vestes et vêtements personnalisés pour entreprises."], ["Cadeaux d’entreprise", "Cadeaux pour clients, équipes, événements et campagnes spéciales."]],
      steps: [["Choisissez une catégorie", "Parcourez les familles de produits et trouvez rapidement des options pour votre campagne."], ["Définissez la couleur et la quantité", "Consultez le stock, les tarifs dégressifs et la disponibilité avant de commander."], ["Créez une maquette ou achetez directement", "Personnalisez le produit si possible ou ajoutez-le directement au panier."], ["Finalisez votre commande", "Vérifiez les informations au paiement et confirmez votre achat en toute sécurité."]],
      benefits: ["Achat direct en ligne", "Tarifs dégressifs", "Stock et couleurs par produit", "Produits personnalisables", "Catalogue continuellement enrichi", "Expédition sous 24 h*"],
      smart: { request: "Que recherchez-vous ?", placeholder: "500 bouteilles durables à moins de 3 € pour un salon", hint: "Recherchez un produit ou indiquez-nous simplement vos besoins.", suggestions: "Je ne sais pas encore. Montrez-moi vos suggestions.", suggestionsHint: "Indiquez simplement la quantité et le budget disponible.", quantity: "Quantité", budget: "Budget total", submit: "Afficher les suggestions" },
    },
  },

es: {
    common: { backHome: "Volver al inicio", backCategories: "Volver a las categor\u00EDas", searchProducts: "Buscar productos", viewProducts: "Ver productos", product: "producto", products: "productos", available: "disponibles", retry: "Int\u00E9ntalo de nuevo.", quote: "Precio bajo consulta", stock: "Stock", quantity: "Cantidad", personalization: "Personalizaci\u00F3n", setup: "Preparaci\u00F3n", extras: "Extras", vat: "IVA", total: "Total", confirm: "Por confirmar", units: "unidades" },
    catalog: { eyebrow: "Cat\u00E1logo", title: "Categor\u00EDas de productos", intro: "Explora el cat\u00E1logo por categor\u00EDas y encuentra r\u00E1pidamente productos para campa\u00F1as, eventos, equipos, clientes y acciones empresariales.", loadError: "No se han podido cargar las categor\u00EDas.", emptyTitle: "Todav\u00EDa no hay categor\u00EDas disponibles", emptyText: "El cat\u00E1logo est\u00E1 en preparaci\u00F3n.", searchEyebrow: "Buscar", searchTitle: "B\u00FAsqueda de productos", searchIntro: "Encuentra productos promocionales, merchandising corporativo, regalos empresariales y ropa promocional para campa\u00F1as, eventos y equipos.", placeholder: "Buscar por producto, SKU, material, marca o categor\u00EDa", type: "Tipo", allTypes: "Todos los tipos", material: "Material", allMaterials: "Todos los materiales", customisation: "Personalizaci\u00F3n", all: "Todos", customisable: "Personalizable", notCustomisable: "No personalizable", sort: "Ordenar", featuredFirst: "Destacados primero", newest: "M\u00E1s recientes", nameAsc: "Nombre A-Z", nameDesc: "Nombre Z-A", shown: "producto(s) mostrado(s)", start: "Introduce una b\u00FAsqueda o utiliza los filtros para encontrar productos.", clear: "Borrar b\u00FAsqueda", readyTitle: "Todo listo para buscar", readyText: "Introduce el nombre de un producto, SKU, material o marca. Tambi\u00E9n puedes filtrar por tipo, material o personalizaci\u00F3n.", noResults: "Sin resultados", noResultsText: "Prueba a buscar botella, taza, camiseta, algod\u00F3n, metal o un SKU.", featured: "Destacado", customizable: "Personalizable", noImage: "No hay imagen disponible", from: "Desde", viewProduct: "Ver producto" },
    cart: { continueShopping: "Seguir comprando", title: "Carrito", intro: "Revisa los productos y precios antes de continuar a la compra.", unit: "Precio unitario", summary: "Resumen", checkout: "Continuar a la compra", secure: "Stripe procesar\u00E1 el pago de forma segura.", freeShipping: "Env\u00EDo gratis en pedidos de 50 \u20AC o m\u00E1s.", freeShippingUnlocked: "Ya tienes env\u00EDo gratis en este pedido.", freeShippingRemaining: "A\u00F1ade {amount} m\u00E1s para conseguir env\u00EDo gratis.", empty: "Tu carrito est\u00E1 vac\u00EDo", emptyText: "A\u00F1ade productos al carrito para preparar tu pedido.", find: "Encontrar productos" },
    checkout: { back: "Volver al carrito", destination: "Destino", detailsAddress: "Datos y direcci\u00F3n", shipping: "Env\u00EDo", shippingTime: "Entrega y plazo", payment: "Pago", reviewPayment: "Revisi\u00F3n y pago", step: "Paso 1 de 3", title: "Destino del pedido", intro: "Confirma tus datos e indica la direcci\u00F3n donde deseas recibir el pedido.", order: "Pedido", summary: "Resumen", configured: "Personalizaci\u00F3n configurada", location: "Ubicaci\u00F3n", technique: "T\u00E9cnica", logo: "Logotipo", notUploaded: "Todav\u00EDa sin cargar", shippingCalc: "Por calcular", currentTotal: "Total actual", taxNote: "El env\u00EDo y el IVA se a\u00F1adir\u00E1n antes del pago.", next: "Siguiente paso", nextText: "En el env\u00EDo podr\u00E1s elegir el m\u00E9todo de entrega, consultar el plazo y confirmar el coste.", securePayment: "Pago seguro", secureText: "El pago solo se solicita despu\u00E9s de elegir el env\u00EDo y revisar el importe final." },
    product: { back: "Volver a las categor\u00EDas", backTo: "Volver a", backProduct: "Volver al producto", customizeStep: "Paso 2 \u00B7 Personalizaci\u00F3n", customizeIntro: "Elige la ubicaci\u00F3n y la t\u00E9cnica, carga tu logotipo y confirma la maqueta para continuar directamente a la compra.", colourSize: "Color / talla", selected: "Seleccionado", noAreas: "Este producto todav\u00EDa no tiene \u00E1reas de personalizaci\u00F3n disponibles", noAreasText: "Puedes volver al producto y a\u00F1adirlo al carrito sin personalizaci\u00F3n." },
    header: { categories: "Categor\u00EDas", guides: "Gu\u00EDas B2B", help: "Ayuda", search: "Buscar", cart: "Carrito", account: "Mi cuenta", signIn: "Iniciar sesi\u00F3n", admin: "Administraci\u00F3n", store: "Ver tienda", home: "p\u00E1gina de inicio" },
    footer: {
        discover: "Descubrir", support: "Asistencia", intro: "La forma inteligente de encontrar, personalizar y comprar merchandising para tu empresa.", trySmart: "Probar Smart Merch", commercialSupport: "Asistencia comercial", rights: "Todos los derechos reservados.", complaints: "Libro de reclamaciones",
        links: { categories: "Categor\u00EDas", solutions: "Soluciones", applications: "Aplicaciones", industries: "Sectores", guides: "Gu\u00EDas", selections: "Selecciones 360", customization: "Personalizaci\u00F3n", sustainability: "Sostenibilidad", blog: "Blog", search: "Buscar productos", about: "Sobre 360", how: "C\u00F3mo funciona", quality: "Calidad y transparencia", delivery: "Entregas y plazos", methodology: "Metodolog\u00EDa editorial", buy: "C\u00F3mo comprar", request: "Solicitud personalizada", account: "Mi cuenta", cart: "Carrito" },
    },
    home: {
        title: "Encuentra el merchandising adecuado en segundos.", intro: "Dinos qu\u00E9 necesitas, cu\u00E1ntas unidades quieres, tu presupuesto y cu\u00E1ndo necesitas recibirlo.", badge: "La forma inteligente de comprar merchandising", categories: "Categor\u00EDas", seeCategories: "Ver categor\u00EDas", highlights: "Productos destacados", categoryTitle: "\u00BFProductos promocionales y regalos corporativos? Los tenemos.", categoryIntro: "Explora nuestras principales categor\u00EDas de productos.", allCategories: "Ver todas las categor\u00EDas", explore: "Explorar", seeProducts: "Ver productos", howToBuy: "C\u00F3mo comprar", howTitle: "De la elecci\u00F3n del producto al pedido en pocos pasos.", products: "Productos", exploreCatalog: "Explorar cat\u00E1logo", catalogPreparing: "El cat\u00E1logo est\u00E1 en preparaci\u00F3n.", b2b: "Ventajas B2B", b2bTitle: "Una experiencia pensada para empresas.", b2bIntro: "360 Merchandising agiliza la compra y personalizaci\u00F3n de productos promocionales, reduce las solicitudes manuales y facilita la elecci\u00F3n por categor\u00EDa, color, stock, cantidad y personalizaci\u00F3n.", catalog: "Cat\u00E1logo", ctaTitle: "Encuentra el producto adecuado para la pr\u00F3xima campa\u00F1a de tu empresa.", from: "Desde", quote: "Precio bajo consulta", stock: "Stock", product: "Ver producto", available: "Producto disponible",
        categoryCards: [["Productos promocionales", "Productos personalizados para campa\u00F1as, eventos, ferias y activaciones de marca."], ["Merchandising corporativo", "Soluciones de marca para empresas, equipos, clientes y campa\u00F1as comerciales."], ["Ropa promocional", "Camisetas, polos, sudaderas, chaquetas y ropa personalizada para empresas."], ["Regalos empresariales", "Regalos corporativos para clientes, equipos, eventos y campa\u00F1as especiales."]],
        steps: [["Elige una categor\u00EDa", "Explora las familias de productos y encuentra opciones para tu campa\u00F1a r\u00E1pidamente."], ["Elige color y cantidad", "Consulta stock, precios por cantidad y disponibilidad antes de comprar."], ["Crea una maqueta o compra directamente", "Personaliza el producto cuando sea posible o a\u00F1\u00E1delo directamente al carrito."], ["Completa tu pedido", "Revisa los datos en la compra y confirma el pedido de forma segura."]],
        benefits: ["Compra directa online", "Precios por cantidad", "Stock y colores por producto", "Productos con personalizaci\u00F3n disponible", "Cat\u00E1logo actualizado continuamente", "Env\u00EDos en 24 horas*"],
        smart: { request: "\u00BFQu\u00E9 est\u00E1s buscando?", placeholder: "500 botellas sostenibles por menos de 3 \u20AC para una feria", hint: "Busca un producto o simplemente cu\u00E9ntanos qu\u00E9 necesitas.", suggestions: "No lo tengo claro. Mu\u00E9strame sugerencias.", suggestionsHint: "Indica \u00FAnicamente la cantidad y el presupuesto disponible.", quantity: "Cantidad", budget: "Presupuesto total", submit: "Mostrar sugerencias" },
    },
},
de: {
    common: { backHome: "Zur Startseite", backCategories: "Zur\u00FCck zu den Kategorien", searchProducts: "Produkte suchen", viewProducts: "Produkte ansehen", product: "Produkt", products: "Produkte", available: "verf\u00FCgbar", retry: "Bitte versuchen Sie es erneut.", quote: "Preis auf Anfrage", stock: "Bestand", quantity: "Menge", personalization: "Personalisierung", setup: "Einrichtung", extras: "Extras", vat: "MwSt.", total: "Gesamtbetrag", confirm: "Noch zu best\u00E4tigen", units: "St\u00FCck" },
    catalog: { eyebrow: "Katalog", title: "Produktkategorien", intro: "Durchsuchen Sie den Katalog nach Kategorien und finden Sie schnell Produkte f\u00FCr Kampagnen, Veranstaltungen, Teams, Kunden und Unternehmensaktionen.", loadError: "Die Kategorien konnten nicht geladen werden.", emptyTitle: "Noch keine Kategorien verf\u00FCgbar", emptyText: "Der Katalog wird vorbereitet.", searchEyebrow: "Suchen", searchTitle: "Produktsuche", searchIntro: "Finden Sie Werbeartikel, Unternehmensmerchandising, Firmengeschenke und Werbekleidung f\u00FCr Kampagnen, Veranstaltungen und Teams.", placeholder: "Nach Produkt, SKU, Material, Marke oder Kategorie suchen", type: "Typ", allTypes: "Alle Typen", material: "Material", allMaterials: "Alle Materialien", customisation: "Personalisierung", all: "Alle", customisable: "Personalisierbar", notCustomisable: "Nicht personalisierbar", sort: "Sortieren", featuredFirst: "Highlights zuerst", newest: "Neueste zuerst", nameAsc: "Name A\u2013Z", nameDesc: "Name Z\u2013A", shown: "angezeigte Produkte", start: "Geben Sie einen Suchbegriff ein oder nutzen Sie die Filter.", clear: "Suche l\u00F6schen", readyTitle: "Bereit f\u00FCr die Suche", readyText: "Geben Sie Produktname, SKU, Material oder Marke ein. Sie k\u00F6nnen auch nach Typ, Material oder Personalisierung filtern.", noResults: "Keine Ergebnisse", noResultsText: "Suchen Sie beispielsweise nach Flasche, Tasse, T-Shirt, Baumwolle, Metall oder einer SKU.", featured: "Highlight", customizable: "Personalisierbar", noImage: "Kein Bild verf\u00FCgbar", from: "Ab", viewProduct: "Produkt ansehen" },
    cart: { continueShopping: "Weiter einkaufen", title: "Warenkorb", intro: "Pr\u00FCfen Sie Produkte und Preise, bevor Sie zur Kasse gehen.", unit: "St\u00FCckpreis", summary: "Zusammenfassung", checkout: "Zur Kasse", secure: "Die Zahlung wird sicher durch Stripe verarbeitet.", freeShipping: "Kostenloser Versand ab 50 \u20AC Bestellwert.", freeShippingUnlocked: "Sie erhalten f\u00FCr diese Bestellung kostenlosen Versand.", freeShippingRemaining: "F\u00FCgen Sie weitere {amount} hinzu und erhalten Sie kostenlosen Versand.", empty: "Ihr Warenkorb ist leer", emptyText: "F\u00FCgen Sie Produkte zum Warenkorb hinzu, um Ihre Bestellung vorzubereiten.", find: "Produkte finden" },
    checkout: { back: "Zur\u00FCck zum Warenkorb", destination: "Lieferadresse", detailsAddress: "Angaben und Adresse", shipping: "Versand", shippingTime: "Lieferung und Lieferzeit", payment: "Zahlung", reviewPayment: "Pr\u00FCfung und Zahlung", step: "Schritt 1 von 3", title: "Lieferadresse der Bestellung", intro: "Best\u00E4tigen Sie Ihre Kundendaten und geben Sie die gew\u00FCnschte Lieferadresse ein.", order: "Bestellung", summary: "Zusammenfassung", configured: "Personalisierung konfiguriert", location: "Position", technique: "Technik", logo: "Logo", notUploaded: "Noch nicht hochgeladen", shippingCalc: "Wird berechnet", currentTotal: "Aktueller Gesamtbetrag", taxNote: "Versand und MwSt. werden vor der Zahlung hinzugef\u00FCgt.", next: "N\u00E4chster Schritt", nextText: "Beim Versand k\u00F6nnen Sie die Lieferart w\u00E4hlen, die Lieferzeit pr\u00FCfen und die Kosten best\u00E4tigen.", securePayment: "Sichere Zahlung", secureText: "Die Zahlung wird erst nach Auswahl des Versands und Pr\u00FCfung des Endbetrags angefordert." },
    product: { back: "Zur\u00FCck zu den Kategorien", backTo: "Zur\u00FCck zu", backProduct: "Zur\u00FCck zum Produkt", customizeStep: "Schritt 2 \u00B7 Personalisierung", customizeIntro: "W\u00E4hlen Sie Position und Technik, laden Sie Ihr Logo hoch und best\u00E4tigen Sie die Vorschau, um direkt zur Kasse zu gehen.", colourSize: "Farbe / Gr\u00F6\u00DFe", selected: "Ausgew\u00E4hlt", noAreas: "F\u00FCr dieses Produkt sind noch keine Personalisierungsfl\u00E4chen verf\u00FCgbar", noAreasText: "Sie k\u00F6nnen zum Produkt zur\u00FCckkehren und es ohne Personalisierung in den Warenkorb legen." },
    header: { categories: "Kategorien", guides: "B2B-Ratgeber", help: "Hilfe", search: "Suchen", cart: "Warenkorb", account: "Mein Konto", signIn: "Anmelden", admin: "Verwaltung", store: "Shop ansehen", home: "Startseite" },
    footer: {
        discover: "Entdecken", support: "Unterst\u00FCtzung", intro: "Merchandising f\u00FCr Ihr Unternehmen clever finden, personalisieren und kaufen.", trySmart: "Smart Merch ausprobieren", commercialSupport: "Verkaufsberatung", rights: "Alle Rechte vorbehalten.", complaints: "Beschwerdebuch",
        links: { categories: "Kategorien", solutions: "L\u00F6sungen", applications: "Einsatzbereiche", industries: "Branchen", guides: "Ratgeber", selections: "360-Auswahl", customization: "Personalisierung", sustainability: "Nachhaltigkeit", blog: "Blog", search: "Produkte suchen", about: "\u00DCber 360", how: "So funktioniert es", quality: "Qualit\u00E4t und Transparenz", delivery: "Lieferung und Lieferzeiten", methodology: "Redaktionelle Methodik", buy: "So kaufen Sie ein", request: "Individuelle Anfrage", account: "Mein Konto", cart: "Warenkorb" },
    },
    home: {
        title: "Finden Sie in Sekunden das passende Merchandising.", intro: "Sagen Sie uns, was Sie ben\u00F6tigen, wie viele St\u00FCck Sie w\u00FCnschen, welches Budget Sie haben und wann die Lieferung erfolgen soll.", badge: "Merchandising clever einkaufen", categories: "Kategorien", seeCategories: "Kategorien ansehen", highlights: "Ausgew\u00E4hlte Produkte", categoryTitle: "Werbeartikel und Firmengeschenke? Haben wir.", categoryIntro: "Entdecken Sie unsere wichtigsten Produktkategorien.", allCategories: "Alle Kategorien ansehen", explore: "Entdecken", seeProducts: "Produkte ansehen", howToBuy: "So kaufen Sie ein", howTitle: "Von der Produktauswahl zur Bestellung in wenigen Schritten.", products: "Produkte", exploreCatalog: "Katalog entdecken", catalogPreparing: "Der Katalog wird vorbereitet.", b2b: "B2B-Vorteile", b2bTitle: "Ein Einkaufserlebnis f\u00FCr Unternehmen.", b2bIntro: "360 Merchandising beschleunigt Kauf und Personalisierung von Werbeartikeln, reduziert manuelle Anfragen und erleichtert die Auswahl nach Kategorie, Farbe, Bestand, Menge und Personalisierung.", catalog: "Katalog", ctaTitle: "Finden Sie das passende Produkt f\u00FCr die n\u00E4chste Kampagne Ihres Unternehmens.", from: "Ab", quote: "Preis auf Anfrage", stock: "Bestand", product: "Produkt ansehen", available: "Produkt verf\u00FCgbar",
        categoryCards: [["Werbeartikel", "Personalisierte Produkte f\u00FCr Kampagnen, Veranstaltungen, Messen und Markenaktivierungen."], ["Unternehmensmerchandising", "Markenl\u00F6sungen f\u00FCr Unternehmen, Teams, Kunden und Vertriebskampagnen."], ["Werbekleidung", "T-Shirts, Poloshirts, Sweatshirts, Jacken und personalisierte Kleidung f\u00FCr Unternehmen."], ["Firmengeschenke", "Firmengeschenke f\u00FCr Kunden, Teams, Veranstaltungen und besondere Kampagnen."]],
        steps: [["Kategorie w\u00E4hlen", "Durchsuchen Sie Produktgruppen und finden Sie schnell Optionen f\u00FCr Ihre Kampagne."], ["Farbe und Menge w\u00E4hlen", "Pr\u00FCfen Sie Bestand, Mengenpreise und Verf\u00FCgbarkeit vor der Bestellung."], ["Vorschau erstellen oder direkt kaufen", "Personalisieren Sie das Produkt, sofern m\u00F6glich, oder legen Sie es direkt in den Warenkorb."], ["Bestellung abschlie\u00DFen", "Pr\u00FCfen Sie Ihre Angaben an der Kasse und best\u00E4tigen Sie den Kauf sicher."]],
        benefits: ["Direkt online kaufen", "Mengenpreise", "Bestand und Farben je Produkt", "Produkte mit Personalisierungsoptionen", "Laufend aktualisierter Katalog", "Versand innerhalb von 24 Stunden*"],
        smart: { request: "Was suchen Sie?", placeholder: "500 nachhaltige Flaschen unter 3 \u20AC f\u00FCr eine Messe", hint: "Suchen Sie nach einem Produkt oder sagen Sie uns einfach, was Sie ben\u00F6tigen.", suggestions: "Ich bin mir nicht sicher. Zeigen Sie mir Vorschl\u00E4ge.", suggestionsHint: "Geben Sie einfach Menge und verf\u00FCgbares Budget an.", quantity: "Menge", budget: "Gesamtbudget", submit: "Vorschl\u00E4ge anzeigen" },
    },
},
it: {
    common: { backHome: "Torna alla pagina iniziale", backCategories: "Torna alle categorie", searchProducts: "Cerca prodotti", viewProducts: "Vedi prodotti", product: "prodotto", products: "prodotti", available: "disponibili", retry: "Riprova.", quote: "Prezzo su richiesta", stock: "Disponibilit\u00E0", quantity: "Quantit\u00E0", personalization: "Personalizzazione", setup: "Preparazione", extras: "Extra", vat: "IVA", total: "Totale", confirm: "Da confermare", units: "unit\u00E0" },
    catalog: { eyebrow: "Catalogo", title: "Categorie di prodotti", intro: "Esplora il catalogo per categoria e trova rapidamente prodotti per campagne, eventi, team, clienti e iniziative aziendali.", loadError: "Impossibile caricare le categorie.", emptyTitle: "Nessuna categoria ancora disponibile", emptyText: "Il catalogo \u00E8 in preparazione.", searchEyebrow: "Cerca", searchTitle: "Ricerca prodotti", searchIntro: "Trova prodotti promozionali, merchandising aziendale, regali d'impresa e abbigliamento promozionale per campagne, eventi e team.", placeholder: "Cerca per prodotto, SKU, materiale, marchio o categoria", type: "Tipo", allTypes: "Tutti i tipi", material: "Materiale", allMaterials: "Tutti i materiali", customisation: "Personalizzazione", all: "Tutti", customisable: "Personalizzabile", notCustomisable: "Non personalizzabile", sort: "Ordina", featuredFirst: "In evidenza prima", newest: "Pi\u00F9 recenti", nameAsc: "Nome A-Z", nameDesc: "Nome Z-A", shown: "prodotti mostrati", start: "Inserisci una ricerca o usa i filtri per trovare prodotti.", clear: "Cancella ricerca", readyTitle: "Pronto per la ricerca", readyText: "Inserisci nome del prodotto, SKU, materiale o marchio. Puoi anche filtrare per tipo, materiale o personalizzazione.", noResults: "Nessun risultato", noResultsText: "Prova a cercare bottiglia, tazza, t-shirt, cotone, metallo o uno SKU.", featured: "In evidenza", customizable: "Personalizzabile", noImage: "Nessuna immagine disponibile", from: "Da", viewProduct: "Vedi prodotto" },
    cart: { continueShopping: "Continua gli acquisti", title: "Carrello", intro: "Verifica prodotti e prezzi prima di procedere all'acquisto.", unit: "Prezzo unitario", summary: "Riepilogo", checkout: "Procedi all'acquisto", secure: "Il pagamento verr\u00E0 elaborato in modo sicuro da Stripe.", freeShipping: "Spedizione gratuita per ordini da 50 \u20AC.", freeShippingUnlocked: "Hai ottenuto la spedizione gratuita per questo ordine.", freeShippingRemaining: "Aggiungi altri {amount} per ottenere la spedizione gratuita.", empty: "Il tuo carrello \u00E8 vuoto", emptyText: "Aggiungi prodotti al carrello per preparare il tuo ordine.", find: "Trova prodotti" },
    checkout: { back: "Torna al carrello", destination: "Destinazione", detailsAddress: "Dati e indirizzo", shipping: "Spedizione", shippingTime: "Consegna e tempi", payment: "Pagamento", reviewPayment: "Riepilogo e pagamento", step: "Passaggio 1 di 3", title: "Destinazione dell'ordine", intro: "Conferma i tuoi dati e inserisci l'indirizzo dove desideri ricevere l'ordine.", order: "Ordine", summary: "Riepilogo", configured: "Personalizzazione configurata", location: "Posizione", technique: "Tecnica", logo: "Logo", notUploaded: "Non ancora caricato", shippingCalc: "Da calcolare", currentTotal: "Totale attuale", taxNote: "Spedizione e IVA verranno aggiunte prima del pagamento.", next: "Passaggio successivo", nextText: "Nella spedizione puoi scegliere il metodo di consegna, verificare i tempi e confermare il costo.", securePayment: "Pagamento sicuro", secureText: "Il pagamento viene richiesto solo dopo la scelta della spedizione e la verifica dell'importo finale." },
    product: { back: "Torna alle categorie", backTo: "Torna a", backProduct: "Torna al prodotto", customizeStep: "Passaggio 2 \u00B7 Personalizzazione", customizeIntro: "Scegli posizione e tecnica, carica il logo e conferma la bozza per procedere direttamente all'acquisto.", colourSize: "Colore / taglia", selected: "Selezionato", noAreas: "Questo prodotto non ha ancora aree di personalizzazione disponibili", noAreasText: "Puoi tornare al prodotto e aggiungerlo al carrello senza personalizzazione." },
    header: { categories: "Categorie", guides: "Guide B2B", help: "Aiuto", search: "Cerca", cart: "Carrello", account: "Il mio account", signIn: "Accedi", admin: "Amministrazione", store: "Vedi negozio", home: "pagina iniziale" },
    footer: {
        discover: "Scopri", support: "Assistenza", intro: "Il modo intelligente di trovare, personalizzare e acquistare merchandising per la tua azienda.", trySmart: "Prova Smart Merch", commercialSupport: "Assistenza commerciale", rights: "Tutti i diritti riservati.", complaints: "Libro dei reclami",
        links: { categories: "Categorie", solutions: "Soluzioni", applications: "Applicazioni", industries: "Settori", guides: "Guide", selections: "Selezioni 360", customization: "Personalizzazione", sustainability: "Sostenibilit\u00E0", blog: "Blog", search: "Cerca prodotti", about: "Chi \u00E8 360", how: "Come funziona", quality: "Qualit\u00E0 e trasparenza", delivery: "Consegne e tempi", methodology: "Metodologia editoriale", buy: "Come acquistare", request: "Richiesta personalizzata", account: "Il mio account", cart: "Carrello" },
    },
    home: {
        title: "Trova il merchandising giusto in pochi secondi.", intro: "Dicci cosa ti serve, quante unit\u00E0 desideri, il tuo budget e quando vuoi riceverle.", badge: "Il modo intelligente di acquistare merchandising", categories: "Categorie", seeCategories: "Vedi categorie", highlights: "Prodotti in evidenza", categoryTitle: "Prodotti promozionali e regali aziendali? Ci sono.", categoryIntro: "Esplora le nostre principali categorie di prodotti.", allCategories: "Vedi tutte le categorie", explore: "Esplora", seeProducts: "Vedi prodotti", howToBuy: "Come acquistare", howTitle: "Dalla scelta del prodotto all'ordine in pochi semplici passaggi.", products: "Prodotti", exploreCatalog: "Esplora catalogo", catalogPreparing: "Il catalogo \u00E8 in preparazione.", b2b: "Vantaggi B2B", b2bTitle: "Un'esperienza pensata per le aziende.", b2bIntro: "360 Merchandising accelera l'acquisto e la personalizzazione dei prodotti promozionali, riduce le richieste manuali e facilita la scelta per categoria, colore, disponibilit\u00E0, quantit\u00E0 e personalizzazione.", catalog: "Catalogo", ctaTitle: "Trova il prodotto giusto per la prossima campagna della tua azienda.", from: "Da", quote: "Prezzo su richiesta", stock: "Disponibilit\u00E0", product: "Vedi prodotto", available: "Prodotto disponibile",
        categoryCards: [["Prodotti promozionali", "Prodotti personalizzati per campagne, eventi, fiere e attivazioni del marchio."], ["Merchandising aziendale", "Soluzioni di branding per aziende, team, clienti e campagne commerciali."], ["Abbigliamento promozionale", "T-shirt, polo, felpe, giacche e abbigliamento personalizzato per aziende."], ["Regali aziendali", "Regali aziendali per clienti, team, eventi e campagne speciali."]],
        steps: [["Scegli una categoria", "Esplora le famiglie di prodotti e trova rapidamente opzioni per la tua campagna."], ["Scegli colore e quantit\u00E0", "Controlla scorte, prezzi per quantit\u00E0 e disponibilit\u00E0 prima di ordinare."], ["Crea una bozza o acquista direttamente", "Personalizza il prodotto quando possibile o aggiungilo direttamente al carrello."], ["Completa il tuo ordine", "Verifica i tuoi dati alla cassa e conferma l'acquisto in sicurezza."]],
        benefits: ["Acquisto diretto online", "Prezzi per quantit\u00E0", "Disponibilit\u00E0 e colori per prodotto", "Prodotti con personalizzazione disponibile", "Catalogo costantemente aggiornato", "Spedizioni in 24 ore*"],
        smart: { request: "Cosa stai cercando?", placeholder: "500 bottiglie sostenibili sotto i 3 \u20AC per una fiera", hint: "Cerca un prodotto o dicci semplicemente cosa ti serve.", suggestions: "Non sono sicuro. Mostrami dei suggerimenti.", suggestionsHint: "Indica solo la quantit\u00E0 e il budget disponibile.", quantity: "Quantit\u00E0", budget: "Budget totale", submit: "Mostra suggerimenti" },
    },
},
} as const;

export function getMessages(locale: SiteLocale) {
  return messages[locale];
}
