import type { SiteLocale } from "@/lib/i18n/config";

const messages = {
  pt: {
    header: { categories: "Categorias", guides: "Guias B2B", help: "Ajuda", search: "Pesquisar", cart: "Carrinho", account: "Área Cliente", signIn: "Entrar", admin: "Admin", store: "Ver loja", home: "página inicial" },
    footer: {
      discover: "Descobrir", support: "Apoio", intro: "A forma inteligente de encontrar, personalizar e comprar merchandising para a sua empresa.", trySmart: "Experimentar o Smart Merch", commercialSupport: "Apoio comercial", rights: "Todos os direitos reservados.", complaints: "Livro de Reclamações",
      links: { categories: "Categorias", solutions: "Soluções", applications: "Aplicações", industries: "Indústrias", guides: "Guias", selections: "Seleções 360", customization: "Personalização", sustainability: "Sustentabilidade", blog: "Blog", search: "Pesquisar produtos", about: "Sobre a 360", how: "Como funciona", quality: "Qualidade e transparência", delivery: "Entregas e prazos", methodology: "Metodologia editorial", buy: "Como comprar", request: "Pedido personalizado", account: "Área de cliente", cart: "Carrinho" },
    },
    home: {
      title: "Encontre o merchandising certo em segundos.", intro: "Diga-nos o que precisa, quantas unidades pretende, quanto quer gastar e quando precisa de receber.", badge: "A forma inteligente de comprar merchandising", categories: "Categorias", seeCategories: "Ver categorias", highlights: "Produtos em destaque", categoryTitle: "Brindes & Gifts? Temos.", categoryIntro: "Explore as nossas categorias.", allCategories: "Ver todas as categorias", explore: "Explorar", seeProducts: "Ver produtos", howToBuy: "Como comprar", howTitle: "Da escolha do produto à encomenda em poucos passos.", products: "Produtos", exploreCatalog: "Explorar catálogo", catalogPreparing: "O catálogo está a ser preparado.", b2b: "Vantagens B2B", b2bTitle: "Uma experiência pensada para empresas.", b2bIntro: "A 360 Merchandising foi desenhada para acelerar a compra e a personalização de produtos promocionais, reduzindo pedidos manuais e facilitando a escolha por categoria, cor, stock, quantidade e personalização.", catalog: "Catálogo", ctaTitle: "Encontra o produto certo para a próxima campanha da tua empresa.", from: "Desde", quote: "Sob consulta", stock: "Stock", product: "Ver produto", available: "Produto disponível",
      categoryCards: [
        ["Brindes Promocionais", "Produtos personalizados para campanhas, eventos, feiras e ativações de marca."],
        ["Merchandising Corporativo", "Soluções de branding para empresas, equipas, clientes e ações comerciais."],
        ["Vestuário Promocional", "T-shirts, polos, sweats, casacos e vestuário personalizado para empresas."],
        ["Gifts Empresariais", "Presentes corporativos para clientes, equipas, eventos e campanhas especiais."],
      ],
      steps: [["Escolhe a categoria", "Explora o catálogo por famílias de produto e encontra rapidamente opções para a tua campanha."], ["Define cor e quantidade", "Consulta stock, escalões de preço e disponibilidade antes de avançar com a encomenda."], ["Cria maquete ou compra direto", "Personaliza o produto quando aplicável ou adiciona diretamente ao carrinho."], ["Finaliza a encomenda", "Revê os dados no checkout e confirma a compra de forma simples e segura."]],
      benefits: ["Compra direta online", "Escalões de preço por quantidade", "Stock e cores por produto", "Produtos com personalização disponível", "Catálogo em permanente evolução", "Envios em 24H*"],
      smart: { request: "O que procura?", placeholder: "500 garrafas sustentáveis até 3 € para uma feira", hint: "Pode pesquisar por produto ou simplesmente dizer-nos o que precisa.", suggestions: "Não sei! Aceito as vossas sugestões.", suggestionsHint: "Indique apenas a quantidade e o orçamento disponível.", quantity: "Quantidade", budget: "Orçamento total", submit: "Mostrar sugestões" },
    },
  },
  en: {
    header: { categories: "Categories", guides: "B2B Guides", help: "Help", search: "Search", cart: "Cart", account: "My account", signIn: "Sign in", admin: "Admin", store: "View store", home: "homepage" },
    footer: {
      discover: "Discover", support: "Support", intro: "The smart way to find, customise and buy merchandise for your business.", trySmart: "Try Smart Merch", commercialSupport: "Sales support", rights: "All rights reserved.", complaints: "Complaints Book",
      links: { categories: "Categories", solutions: "Solutions", applications: "Applications", industries: "Industries", guides: "Guides", selections: "360 Selections", customization: "Customisation", sustainability: "Sustainability", blog: "Blog", search: "Search products", about: "About 360", how: "How it works", quality: "Quality and transparency", delivery: "Delivery and lead times", methodology: "Editorial methodology", buy: "How to buy", request: "Custom request", account: "My account", cart: "Cart" },
    },
    home: {
      title: "Find the right merchandise in seconds.", intro: "Tell us what you need, how many units you want, your budget and when you need delivery.", badge: "The smart way to buy merchandise", categories: "Categories", seeCategories: "View categories", highlights: "Featured products", categoryTitle: "Promotional products and corporate gifts? We have them.", categoryIntro: "Explore our main product categories.", allCategories: "View all categories", explore: "Explore", seeProducts: "View products", howToBuy: "How to buy", howTitle: "From product selection to order in a few simple steps.", products: "Products", exploreCatalog: "Explore catalogue", catalogPreparing: "The catalogue is being prepared.", b2b: "B2B benefits", b2bTitle: "An experience designed for business.", b2bIntro: "360 Merchandising accelerates the purchase and customisation of promotional products, reducing manual requests and making it easier to choose by category, colour, stock, quantity and customisation.", catalog: "Catalogue", ctaTitle: "Find the right product for your company’s next campaign.", from: "From", quote: "Price on request", stock: "Stock", product: "View product", available: "Product available",
      categoryCards: [["Promotional Products", "Custom products for campaigns, events, trade shows and brand activations."], ["Corporate Merchandise", "Branding solutions for companies, teams, clients and sales campaigns."], ["Promotional Clothing", "T-shirts, polos, sweatshirts, jackets and custom clothing for businesses."], ["Corporate Gifts", "Corporate gifts for clients, teams, events and special campaigns."]],
      steps: [["Choose a category", "Browse product families and quickly find options for your campaign."], ["Select colour and quantity", "Check stock, quantity pricing and availability before ordering."], ["Create a mock-up or buy directly", "Customise the product when available or add it directly to your cart."], ["Complete your order", "Review your details at checkout and confirm your purchase securely."]],
      benefits: ["Buy directly online", "Quantity-based pricing", "Product stock and colours", "Products available for customisation", "Continuously updated catalogue", "24-hour dispatch*"],
      smart: { request: "What are you looking for?", placeholder: "500 sustainable bottles under €3 for a trade show", hint: "Search for a product or simply tell us what you need.", suggestions: "I’m not sure. Show me your suggestions.", suggestionsHint: "Simply enter the quantity and available budget.", quantity: "Quantity", budget: "Total budget", submit: "Show suggestions" },
    },
  },
  fr: {
    header: { categories: "Catégories", guides: "Guides B2B", help: "Aide", search: "Rechercher", cart: "Panier", account: "Mon compte", signIn: "Se connecter", admin: "Admin", store: "Voir la boutique", home: "page d’accueil" },
    footer: {
      discover: "Découvrir", support: "Assistance", intro: "La façon intelligente de trouver, personnaliser et acheter du merchandising pour votre entreprise.", trySmart: "Essayer Smart Merch", commercialSupport: "Assistance commerciale", rights: "Tous droits réservés.", complaints: "Livre de réclamations",
      links: { categories: "Catégories", solutions: "Solutions", applications: "Applications", industries: "Secteurs", guides: "Guides", selections: "Sélections 360", customization: "Personnalisation", sustainability: "Durabilité", blog: "Blog", search: "Rechercher des produits", about: "À propos de 360", how: "Comment ça marche", quality: "Qualité et transparence", delivery: "Livraison et délais", methodology: "Méthodologie éditoriale", buy: "Comment acheter", request: "Demande personnalisée", account: "Mon compte", cart: "Panier" },
    },
    home: {
      title: "Trouvez le bon merchandising en quelques secondes.", intro: "Indiquez-nous vos besoins, la quantité souhaitée, votre budget et la date de livraison.", badge: "La façon intelligente d’acheter du merchandising", categories: "Catégories", seeCategories: "Voir les catégories", highlights: "Produits en vedette", categoryTitle: "Objets publicitaires et cadeaux d’entreprise ? Nous les avons.", categoryIntro: "Découvrez nos principales catégories de produits.", allCategories: "Voir toutes les catégories", explore: "Découvrir", seeProducts: "Voir les produits", howToBuy: "Comment acheter", howTitle: "Du choix du produit à la commande en quelques étapes simples.", products: "Produits", exploreCatalog: "Découvrir le catalogue", catalogPreparing: "Le catalogue est en cours de préparation.", b2b: "Avantages B2B", b2bTitle: "Une expérience conçue pour les entreprises.", b2bIntro: "360 Merchandising accélère l’achat et la personnalisation de produits promotionnels, réduit les demandes manuelles et facilite le choix par catégorie, couleur, stock, quantité et personnalisation.", catalog: "Catalogue", ctaTitle: "Trouvez le produit idéal pour la prochaine campagne de votre entreprise.", from: "À partir de", quote: "Prix sur demande", stock: "Stock", product: "Voir le produit", available: "Produit disponible",
      categoryCards: [["Objets publicitaires", "Produits personnalisés pour campagnes, événements, salons et activations de marque."], ["Merchandising d’entreprise", "Solutions de marque pour entreprises, équipes, clients et actions commerciales."], ["Vêtements promotionnels", "T-shirts, polos, sweat-shirts, vestes et vêtements personnalisés pour entreprises."], ["Cadeaux d’entreprise", "Cadeaux pour clients, équipes, événements et campagnes spéciales."]],
      steps: [["Choisissez une catégorie", "Parcourez les familles de produits et trouvez rapidement des options pour votre campagne."], ["Définissez la couleur et la quantité", "Consultez le stock, les tarifs dégressifs et la disponibilité avant de commander."], ["Créez une maquette ou achetez directement", "Personnalisez le produit si possible ou ajoutez-le directement au panier."], ["Finalisez votre commande", "Vérifiez les informations au paiement et confirmez votre achat en toute sécurité."]],
      benefits: ["Achat direct en ligne", "Tarifs dégressifs", "Stock et couleurs par produit", "Produits personnalisables", "Catalogue continuellement enrichi", "Expédition sous 24 h*"],
      smart: { request: "Que recherchez-vous ?", placeholder: "500 bouteilles durables à moins de 3 € pour un salon", hint: "Recherchez un produit ou indiquez-nous simplement vos besoins.", suggestions: "Je ne sais pas encore. Montrez-moi vos suggestions.", suggestionsHint: "Indiquez simplement la quantité et le budget disponible.", quantity: "Quantité", budget: "Budget total", submit: "Afficher les suggestions" },
    },
  },
} as const;

export function getMessages(locale: SiteLocale) {
  return messages[locale];
}
