import type { SiteLocale } from "@/lib/i18n/config";

const messages = {
  pt: {
    common: { backHome: "Voltar à página inicial", backCategories: "Voltar às categorias", searchProducts: "Pesquisar produtos", viewProducts: "Ver produtos", product: "produto", products: "produtos", available: "disponíveis", retry: "Tenta novamente.", quote: "Sob consulta", stock: "Stock", quantity: "Quantidade", personalization: "Personalização", setup: "Preparação", extras: "Extras", vat: "IVA", total: "Total", confirm: "A confirmar", units: "un." },
    catalog: { eyebrow: "Catálogo", title: "Categorias de produtos", intro: "Explora o catálogo por categorias e encontra rapidamente produtos para campanhas, eventos, equipas, clientes e ações empresariais.", loadError: "Não foi possível carregar as categorias.", emptyTitle: "Ainda não existem categorias disponíveis", emptyText: "O catálogo está a ser preparado.", searchEyebrow: "Pesquisa", searchTitle: "Pesquisa de produtos", searchIntro: "Encontra brindes promocionais, merchandising corporativo, gifts empresariais e vestuário promocional para campanhas, eventos e equipas.", placeholder: "Pesquisar por produto, SKU, material, marca ou categoria", type: "Tipo", allTypes: "Todos os tipos", material: "Material", allMaterials: "Todos os materiais", customisation: "Personalização", all: "Todos", customisable: "Personalizáveis", notCustomisable: "Não personalizáveis", sort: "Ordenar", featuredFirst: "Destaques primeiro", newest: "Mais recentes", nameAsc: "Nome A-Z", nameDesc: "Nome Z-A", shown: "produto(s) apresentado(s)", start: "Introduz uma pesquisa ou usa os filtros para encontrar produtos.", clear: "Limpar pesquisa", readyTitle: "Pesquisa pronta a usar", readyText: "Escreve o nome de um produto, SKU, material ou marca. Também podes usar os filtros por tipo, material ou personalização.", noResults: "Sem resultados", noResultsText: "Experimenta pesquisar por garrafa, caneca, t-shirt, algodão, metal ou SKU.", featured: "Destaque", customizable: "Personalizável", noImage: "Sem imagem disponível", from: "Desde", viewProduct: "Ver produto" },
    cart: { continueShopping: "Continuar a comprar", title: "Carrinho", intro: "Revê os produtos e os valores antes de avançar para o checkout.", unit: "Unitário", summary: "Resumo", checkout: "Avançar para checkout", secure: "O pagamento será processado de forma segura através da Stripe.", empty: "O carrinho está vazio", emptyText: "Adiciona produtos ao carrinho para preparar a tua encomenda.", find: "Procurar produtos" },
    checkout: { back: "Voltar ao carrinho", destination: "Destino", detailsAddress: "Dados e morada", shipping: "Expedição", shippingTime: "Transporte e prazo", payment: "Pagamento", reviewPayment: "Revisão e pagamento", step: "Passo 1 de 3", title: "Destino da encomenda", intro: "Confirma os dados do cliente e indica a morada onde pretendes receber a encomenda.", order: "Encomenda", summary: "Resumo", configured: "Personalização configurada", location: "Local", technique: "Técnica", logo: "Logótipo", notUploaded: "Ainda não carregado", shippingCalc: "A calcular", currentTotal: "Total atual", taxNote: "O transporte e o IVA serão adicionados antes do pagamento.", next: "Próximo passo", nextText: "Na expedição poderás escolher o método de transporte, consultar o prazo e confirmar o respetivo custo.", securePayment: "Pagamento seguro", secureText: "O pagamento só será pedido depois da escolha do transporte e da revisão do valor final." },
    product: { back: "Voltar às categorias", backTo: "Voltar a", backProduct: "Voltar ao produto", customizeStep: "Passo 2 · Personalização", customizeIntro: "Escolhe a localização e a técnica, carrega o logótipo e confirma a maquete para avançar diretamente para o checkout.", colourSize: "Cor / tamanho", selected: "Selecionado", noAreas: "Este produto ainda não tem áreas de personalização disponíveis", noAreasText: "Pode voltar ao produto e adicionar ao carrinho sem personalização." },
    header: { categories: "Categorias", guides: "Guias B2B", help: "Ajuda", search: "Pesquisar", cart: "Carrinho", account: "Área Cliente", signIn: "Entrar", admin: "Admin", store: "Ver loja", home: "página inicial" },
    footer: {
      discover: "Descobrir", support: "Apoio", intro: "A forma inteligente de encontrar, personalizar e comprar merchandising para a sua empresa.", trySmart: "Experimentar o Smart Merch", commercialSupport: "Apoio comercial", rights: "Todos os direitos reservados.", complaints: "Livro de Reclamações",
      links: { categories: "Categorias", solutions: "Soluções", applications: "Aplicações", industries: "Indústrias", guides: "Guias", selections: "Seleções 360", customization: "Personalização", sustainability: "Sustentabilidade", blog: "Blog", search: "Pesquisar produtos", about: "Sobre a 360", how: "Como funciona", quality: "Qualidade e transparência", delivery: "Entregas e prazos", methodology: "Metodologia editorial", buy: "Como comprar", request: "Pedido personalizado", account: "Área de cliente", cart: "Carrinho" },
    },
    home: {
      title: "Encontre o merchandising certo em segundos.", intro: "Diga-nos o que precisa, quantas unidades pretende, quanto quer gastar e quando precisa de receber.", badge: "A forma inteligente de comprar merchandising", categories: "Categorias", seeCategories: "Ver categorias", highlights: "Produtos em destaque", categoryTitle: "Brindes & Gifts? Temos.", categoryIntro: "Explore as nossas categorias.", allCategories: "Ver todas as categorias", explore: "Explorar", seeProducts: "Ver produtos", howToBuy: "Como comprar", howTitle: "Da escolha do produto à encomenda em poucos passos.", products: "Produtos", exploreCatalog: "Explorar catálogo", catalogPreparing: "O catálogo está a ser preparado.", b2b: "Vantagens B2B", b2bTitle: "Uma experiência pensada para empresas.", b2bIntro: "A 360 Merchandising foi desenhada para acelerar a compra e a personalização de produtos promocionais, reduzindo pedidos manuais e facilitando a escolha por categoria, cor, stock, quantidade e personalização.", catalog: "Catálogo", ctaTitle: "Encontra o produto certo para a próxima campanha da tua empresa.", from: "Desde", quote: "Sob consulta", stock: "Stock", product: "Ver produto", available: "Produto disponível",
      categoryCards: [
        ["Brindes Promocionais", "Produtos personalizados para campanhas, eventos, feiras e ativações de marca."],
        ["Merchandising Corporativo", "Soluções de branding para empresas, equipas, clientes e ações comerciais."],
        ["Vestuário Promocional", "T-shirts, polos, sweats, casacos e vestuário personalizado para empresas."],
        ["Gifts Empresariais", "Presentes corporativos para clientes, equipas, eventos e campanhas especiais."],
      ],
      steps: [["Escolhe a categoria", "Explora o catálogo por famílias de produto e encontra rapidamente opções para a tua campanha."], ["Define cor e quantidade", "Consulta stock, escalões de preço e disponibilidade antes de avançar com a encomenda."], ["Cria maquete ou compra direto", "Personaliza o produto quando aplicável ou adiciona diretamente ao carrinho."], ["Finaliza a encomenda", "Revê os dados no checkout e confirma a compra de forma simples e segura."]],
      benefits: ["Compra direta online", "Escalões de preço por quantidade", "Stock e cores por produto", "Produtos com personalização disponível", "Catálogo em permanente evolução", "Envios em 24H*"],
      smart: { request: "O que procura?", placeholder: "500 garrafas sustentáveis até 3 € para uma feira", hint: "Pode pesquisar por produto ou simplesmente dizer-nos o que precisa.", suggestions: "Não sei! Aceito as vossas sugestões.", suggestionsHint: "Indique apenas a quantidade e o orçamento disponível.", quantity: "Quantidade", budget: "Orçamento total", submit: "Mostrar sugestões" },
    },
  },
  en: {
    common: { backHome: "Back to homepage", backCategories: "Back to categories", searchProducts: "Search products", viewProducts: "View products", product: "product", products: "products", available: "available", retry: "Please try again.", quote: "Price on request", stock: "Stock", quantity: "Quantity", personalization: "Customisation", setup: "Setup", extras: "Extras", vat: "VAT", total: "Total", confirm: "To be confirmed", units: "units" },
    catalog: { eyebrow: "Catalogue", title: "Product categories", intro: "Browse the catalogue by category and quickly find products for campaigns, events, teams, clients and business initiatives.", loadError: "We could not load the categories.", emptyTitle: "No categories are available yet", emptyText: "The catalogue is being prepared.", searchEyebrow: "Search", searchTitle: "Product search", searchIntro: "Find promotional products, corporate merchandise, business gifts and promotional clothing for campaigns, events and teams.", placeholder: "Search by product, SKU, material, brand or category", type: "Type", allTypes: "All types", material: "Material", allMaterials: "All materials", customisation: "Customisation", all: "All", customisable: "Customisable", notCustomisable: "Not customisable", sort: "Sort", featuredFirst: "Featured first", newest: "Newest", nameAsc: "Name A-Z", nameDesc: "Name Z-A", shown: "product(s) shown", start: "Enter a search or use the filters to find products.", clear: "Clear search", readyTitle: "Ready to search", readyText: "Enter a product name, SKU, material or brand. You can also filter by type, material or customisation.", noResults: "No results", noResultsText: "Try searching for bottle, mug, t-shirt, cotton, metal or a SKU.", featured: "Featured", customizable: "Customisable", noImage: "No image available", from: "From", viewProduct: "View product" },
    cart: { continueShopping: "Continue shopping", title: "Cart", intro: "Review your products and prices before proceeding to checkout.", unit: "Unit price", summary: "Summary", checkout: "Proceed to checkout", secure: "Payment will be processed securely by Stripe.", empty: "Your cart is empty", emptyText: "Add products to your cart to prepare your order.", find: "Find products" },
    checkout: { back: "Back to cart", destination: "Destination", detailsAddress: "Details and address", shipping: "Shipping", shippingTime: "Delivery and lead time", payment: "Payment", reviewPayment: "Review and payment", step: "Step 1 of 3", title: "Order destination", intro: "Confirm your customer details and enter the address where you want to receive your order.", order: "Order", summary: "Summary", configured: "Customisation configured", location: "Location", technique: "Technique", logo: "Logo", notUploaded: "Not uploaded yet", shippingCalc: "To be calculated", currentTotal: "Current total", taxNote: "Shipping and VAT will be added before payment.", next: "Next step", nextText: "During shipping you can choose the delivery method, check the lead time and confirm its cost.", securePayment: "Secure payment", secureText: "Payment is only requested after selecting shipping and reviewing the final amount." },
    product: { back: "Back to categories", backTo: "Back to", backProduct: "Back to product", customizeStep: "Step 2 · Customisation", customizeIntro: "Choose the location and technique, upload your logo and confirm the mock-up to proceed directly to checkout.", colourSize: "Colour / size", selected: "Selected", noAreas: "This product does not yet have customisation areas available", noAreasText: "You can return to the product and add it to your cart without customisation." },
    header: { categories: "Categories", guides: "B2B Guides", help: "Help", search: "Search", cart: "Cart", account: "My account", signIn: "Sign in", admin: "Admin", store: "View store", home: "homepage" },
    footer: {
      discover: "Discover", support: "Support", intro: "The smart way to find, customise and buy merchandise for your business.", trySmart: "Try Smart Merch", commercialSupport: "Sales support", rights: "All rights reserved.", complaints: "Complaints Book",
      links: { categories: "Categories", solutions: "Solutions", applications: "Applications", industries: "Industries", guides: "Guides", selections: "360 Selections", customization: "Customisation", sustainability: "Sustainability", blog: "Blog", search: "Search products", about: "About 360", how: "How it works", quality: "Quality and transparency", delivery: "Delivery and lead times", methodology: "Editorial methodology", buy: "How to buy", request: "Custom request", account: "My account", cart: "Cart" },
    },
    home: {
      title: "Find the right merchandise in seconds.", intro: "Tell us what you need, how many units you want, your budget and when you need delivery.", badge: "The smart way to buy merchandise", categories: "Categories", seeCategories: "View categories", highlights: "Featured products", categoryTitle: "Promotional products and corporate gifts? We have them.", categoryIntro: "Explore our main product categories.", allCategories: "View all categories", explore: "Explore", seeProducts: "View products", howToBuy: "How to buy", howTitle: "From product selection to order in a few simple steps.", products: "Products", exploreCatalog: "Explore catalogue", catalogPreparing: "The catalogue is being prepared.", b2b: "B2B benefits", b2bTitle: "An experience designed for business.", b2bIntro: "360 Merchandising accelerates the purchase and customisation of promotional products, reducing manual requests and making it easier to choose by category, colour, stock, quantity and customisation.", catalog: "Catalogue", ctaTitle: "Find the right product for your company’s next campaign.", from: "From", quote: "Price on request", stock: "Stock", product: "View product", available: "Product available",
      categoryCards: [["Promotional Products", "Custom products for campaigns, events, trade shows and brand activations."], ["Corporate Merchandise", "Branding solutions for companies, teams, clients and sales campaigns."], ["Promotional Clothing", "T-shirts, polos, sweatshirts, jackets and custom clothing for businesses."], ["Corporate Gifts", "Corporate gifts for clients, teams, events and special campaigns."]],
      steps: [["Choose a category", "Browse product families and quickly find options for your campaign."], ["Select colour and quantity", "Check stock, quantity pricing and availability before ordering."], ["Create a mock-up or buy directly", "Customise the product when available or add it directly to your cart."], ["Complete your order", "Review your details at checkout and confirm your purchase securely."]],
      benefits: ["Buy directly online", "Quantity-based pricing", "Product stock and colours", "Products available for customisation", "Continuously updated catalogue", "24-hour dispatch*"],
      smart: { request: "What are you looking for?", placeholder: "500 sustainable bottles under €3 for a trade show", hint: "Search for a product or simply tell us what you need.", suggestions: "I’m not sure. Show me your suggestions.", suggestionsHint: "Simply enter the quantity and available budget.", quantity: "Quantity", budget: "Total budget", submit: "Show suggestions" },
    },
  },
  fr: {
    common: { backHome: "Retour à l’accueil", backCategories: "Retour aux catégories", searchProducts: "Rechercher des produits", viewProducts: "Voir les produits", product: "produit", products: "produits", available: "disponibles", retry: "Veuillez réessayer.", quote: "Prix sur demande", stock: "Stock", quantity: "Quantité", personalization: "Personnalisation", setup: "Préparation", extras: "Suppléments", vat: "TVA", total: "Total", confirm: "À confirmer", units: "unités" },
    catalog: { eyebrow: "Catalogue", title: "Catégories de produits", intro: "Parcourez le catalogue par catégorie et trouvez rapidement des produits pour vos campagnes, événements, équipes, clients et actions d’entreprise.", loadError: "Impossible de charger les catégories.", emptyTitle: "Aucune catégorie n’est encore disponible", emptyText: "Le catalogue est en cours de préparation.", searchEyebrow: "Recherche", searchTitle: "Recherche de produits", searchIntro: "Trouvez des objets publicitaires, du merchandising d’entreprise, des cadeaux professionnels et des vêtements promotionnels.", placeholder: "Rechercher par produit, SKU, matériau, marque ou catégorie", type: "Type", allTypes: "Tous les types", material: "Matériau", allMaterials: "Tous les matériaux", customisation: "Personnalisation", all: "Tous", customisable: "Personnalisables", notCustomisable: "Non personnalisables", sort: "Trier", featuredFirst: "Produits vedettes d’abord", newest: "Plus récents", nameAsc: "Nom A-Z", nameDesc: "Nom Z-A", shown: "produit(s) affiché(s)", start: "Saisissez une recherche ou utilisez les filtres.", clear: "Effacer la recherche", readyTitle: "Recherche prête", readyText: "Saisissez un nom de produit, un SKU, un matériau ou une marque. Vous pouvez également utiliser les filtres.", noResults: "Aucun résultat", noResultsText: "Essayez bouteille, mug, t-shirt, coton, métal ou un SKU.", featured: "En vedette", customizable: "Personnalisable", noImage: "Image indisponible", from: "À partir de", viewProduct: "Voir le produit" },
    cart: { continueShopping: "Continuer mes achats", title: "Panier", intro: "Vérifiez les produits et les prix avant de passer à la commande.", unit: "Prix unitaire", summary: "Récapitulatif", checkout: "Passer à la commande", secure: "Le paiement sera traité de manière sécurisée par Stripe.", empty: "Votre panier est vide", emptyText: "Ajoutez des produits au panier pour préparer votre commande.", find: "Rechercher des produits" },
    checkout: { back: "Retour au panier", destination: "Destination", detailsAddress: "Coordonnées et adresse", shipping: "Expédition", shippingTime: "Transport et délai", payment: "Paiement", reviewPayment: "Vérification et paiement", step: "Étape 1 sur 3", title: "Destination de la commande", intro: "Confirmez vos coordonnées et indiquez l’adresse de livraison de la commande.", order: "Commande", summary: "Récapitulatif", configured: "Personnalisation configurée", location: "Emplacement", technique: "Technique", logo: "Logo", notUploaded: "Pas encore téléchargé", shippingCalc: "À calculer", currentTotal: "Total actuel", taxNote: "Le transport et la TVA seront ajoutés avant le paiement.", next: "Étape suivante", nextText: "Lors de l’expédition, vous pourrez choisir le mode de transport, consulter le délai et confirmer son coût.", securePayment: "Paiement sécurisé", secureText: "Le paiement ne sera demandé qu’après le choix du transport et la vérification du montant final." },
    product: { back: "Retour aux catégories", backTo: "Retour à", backProduct: "Retour au produit", customizeStep: "Étape 2 · Personnalisation", customizeIntro: "Choisissez l’emplacement et la technique, téléchargez votre logo et confirmez la maquette pour passer directement à la commande.", colourSize: "Couleur / taille", selected: "Sélectionné", noAreas: "Ce produit ne dispose pas encore de zones de personnalisation", noAreasText: "Vous pouvez revenir au produit et l’ajouter au panier sans personnalisation." },
    header: { categories: "Catégories", guides: "Guides B2B", help: "Aide", search: "Rechercher", cart: "Panier", account: "Mon compte", signIn: "Se connecter", admin: "Admin", store: "Voir la boutique", home: "page d’accueil" },
    footer: {
      discover: "Découvrir", support: "Assistance", intro: "La façon intelligente de trouver, personnaliser et acheter du merchandising pour votre entreprise.", trySmart: "Essayer Smart Merch", commercialSupport: "Assistance commerciale", rights: "Tous droits réservés.", complaints: "Livre de réclamations",
      links: { categories: "Catégories", solutions: "Solutions", applications: "Applications", industries: "Secteurs", guides: "Guides", selections: "Sélections 360", customization: "Personnalisation", sustainability: "Durabilité", blog: "Blog", search: "Rechercher des produits", about: "À propos de 360", how: "Comment ça marche", quality: "Qualité et transparence", delivery: "Livraison et délais", methodology: "Méthodologie éditoriale", buy: "Comment acheter", request: "Demande personnalisée", account: "Mon compte", cart: "Panier" },
    },
    home: {
      title: "Trouvez le bon merchandising en quelques secondes.", intro: "Indiquez-nous vos besoins, la quantité souhaitée, votre budget et la date de livraison.", badge: "La façon intelligente d’acheter du merchandising", categories: "Catégories", seeCategories: "Voir les catégories", highlights: "Produits en vedette", categoryTitle: "Objets publicitaires et cadeaux d’entreprise ? Nous les avons.", categoryIntro: "Découvrez nos principales catégories de produits.", allCategories: "Voir toutes les catégories", explore: "Découvrir", seeProducts: "Voir les produits", howToBuy: "Comment acheter", howTitle: "Du choix du produit à la commande en quelques étapes simples.", products: "Produits", exploreCatalog: "Découvrir le catalogue", catalogPreparing: "Le catalogue est en cours de préparation.", b2b: "Avantages B2B", b2bTitle: "Une expérience conçue pour les entreprises.", b2bIntro: "360 Merchandising accélère l’achat et la personnalisation de produits promotionnels, réduit les demandes manuelles et facilite le choix par catégorie, couleur, stock, quantité et personnalisation.", catalog: "Catalogue", ctaTitle: "Trouvez le produit idéal pour la prochaine campagne de votre entreprise.", from: "À partir de", quote: "Prix sur demande", stock: "Stock", product: "Voir le produit", available: "Produit disponible",
      categoryCards: [["Objets publicitaires", "Produits personnalisés pour campagnes, événements, salons et activations de marque."], ["Merchandising d’entreprise", "Solutions de marque pour entreprises, équipes, clients et actions commerciales."], ["Vêtements promotionnels", "T-shirts, polos, sweat-shirts, vestes et vêtements personnalisés pour entreprises."], ["Cadeaux d’entreprise", "Cadeaux pour clients, équipes, événements et campagnes spéciales."]],
      steps: [["Choisissez une catégorie", "Parcourez les familles de produits et trouvez rapidement des options pour votre campagne."], ["Définissez la couleur et la quantité", "Consultez le stock, les tarifs dégressifs et la disponibilité avant de commander."], ["Créez une maquette ou achetez directement", "Personnalisez le produit si possible ou ajoutez-le directement au panier."], ["Finalisez votre commande", "Vérifiez les informations au paiement et confirmez votre achat en toute sécurité."]],
      benefits: ["Achat direct en ligne", "Tarifs dégressifs", "Stock et couleurs par produit", "Produits personnalisables", "Catalogue continuellement enrichi", "Expédition sous 24 h*"],
      smart: { request: "Que recherchez-vous ?", placeholder: "500 bouteilles durables à moins de 3 € pour un salon", hint: "Recherchez un produit ou indiquez-nous simplement vos besoins.", suggestions: "Je ne sais pas encore. Montrez-moi vos suggestions.", suggestionsHint: "Indiquez simplement la quantité et le budget disponible.", quantity: "Quantité", budget: "Budget total", submit: "Afficher les suggestions" },
    },
  },
} as const;

export function getMessages(locale: SiteLocale) {
  return messages[locale];
}
